# ---------- CAPÍTULO 14 ----------
chapter('c14', 'Capítulo', '14', 'Contenido madre<br>y piezas hijas',
        'No se trata de copiar y pegar el mismo clip. Se trata de convertir un buen momento en piezas hechas para cada plataforma.', [3],
        lead('Cuando se habla de reutilizar contenido, la mayoría de los dueños de negocio piensan que significa volver a publicar el mismo clip en todas partes. Es una versión de reutilizar, pero no es la más potente.'),
        p('La idea que te propongo es otra: tomar un momento realmente bueno de una pieza principal y sacarle el mayor provecho posible. Una pieza larga, tu <b>contenido madre</b>, puede dar lugar a muchas <b>piezas hijas</b>, cada una pensada para la plataforma donde va a vivir. De un solo momento específico pueden salir varias piezas nativas.'),
        p('Esto no es copiar y pegar, y no es publicar el mismo video corto en todas partes. Es reempaquetar de forma <b>nativa</b>: hacer que cada pieza se vea y se sienta como parte natural de la plataforma en la que se publica. Cada red tiene sus propios hábitos: lo que funciona como video vertical no necesariamente funciona igual como texto o como correo.'),
        h3('Tres pasos'),
        ol(['<b>Creá una pieza madre.</b> Por ejemplo, un video largo en tu plataforma principal o una charla extensa. Es la base de todo lo demás.',
            '<b>Buscá los mejores momentos.</b> Los que te hacen decir “qué buena frase”: una idea que rompe una creencia, una historia o una táctica que puede cambiar cómo piensa tu audiencia, o los pasos exactos para lograr un resultado. No son marcas de tiempo al azar.',
            '<b>Convertilos en piezas nativas.</b> Cada plataforma tiene su propio estilo, así que el mismo momento se vuelve un clip corto, un texto, un correo o un carrusel.']),
        h3('Cómo elegir los mejores momentos'),
        p('No todos los fragmentos sirven. Si le pedís a alguien menos experimentado que te saque clips de un contenido largo, es probable que te devuelva treinta, y que la mitad, o hasta dos tercios, no sean útiles. No funcionan por sí solos: necesitan el contexto de la conversación que los rodea para tener sentido.'),
        keybox('Lo que buscás son momentos autosuficientes',
               ul(['Se entienden sin haber visto el resto.', 'Tienen un comienzo y un final claros.', 'Entregan una idea, una historia con lección o unos pasos concretos.', 'Podrían ser el primer contenido que alguien ve de vos.'])),
        h3('Del mismo momento, distintos envoltorios'),
        p('Una vez que tenés tus momentos, la pregunta es: ¿en qué formato conviene envolver esta idea para que sirva mejor a mi audiencia en la plataforma donde la voy a compartir? Algunas veces alcanzará con recortar un momento y publicarlo como clip corto. Otras veces vas a notar que un intercambio muy bueno de una charla se transforma mejor en una publicación escrita o en un boletín para tu lista de correo.'),
        table2('Un mismo momento', 'Posible versión nativa', [('Una historia con lección', 'Clip corto vertical con el momento clave y un subtítulo claro.'), ('Los tres pasos de un método', 'Carrusel con una idea por lámina.'),
                                                              ('Una opinión fuerte', 'Publicación escrita con la postura y un ejemplo.'), ('Una conversación profunda', 'Correo o boletín para tu lista, con el resumen y una pregunta.')]),
        case('De un video a cinco piezas',
             p('Una consultora graba un video de veinte minutos sobre cómo explicar su servicio a un cliente nuevo. De ahí saca: un clip corto con la idea principal, un carrusel con los tres pasos, una publicación escrita con la historia del ejemplo, un correo para su lista y una pregunta para que su audiencia responda.'),
             learn('Todas comunican el mismo mensaje, pero <b>cada una está empaquetada distinto</b>, según dónde se publica.')),
        h3('Hacelo de a poco'),
        p('No tenés que hacerlo todo desde el primer día. Es normal que al principio publiques el mismo clip en varias plataformas, porque tenés pocos recursos y poco tiempo. Lo importante es que empieces a pensar en esa dirección en lugar de esperar dos, tres o cuatro años.'),
        p('Pensalo como un barco: corregir el rumbo es muy fácil cuando todavía sos una lancha rápida, y mucho más difícil cuando ya sos un transatlántico. Cuanto antes empieces a adaptar contenido a cada plataforma, más fácil será hacerlo cuando crezcas. A medida que sumes más ayuda, vas a ver que tu contenido en cada plataforma se vuelve más contextual y más nativo.'),
        h3('Errores frecuentes'),
        ul(['<b>Publicar el mismo clip en todas partes</b> sin adaptarlo.', '<b>Cortar momentos al azar</b> sin revisar si se entienden solos.', '<b>Sacar demasiados clips</b> y publicar los que no sirven solo por cantidad.',
            '<b>No volver a mirar tu contenido madre.</b> Con cada revisión descubrís momentos nuevos.']),
        exercise('Tu primera cascada',
                 p('Elegí una pieza larga que ya tengas (o una idea para grabar). Revisala y marcá tres momentos autosuficientes.'),
                 p('Para cada momento, escribí en qué formato lo convertirías y en qué plataforma lo publicarías. Anotá cuál sería el primer paso para hacerlo esta semana.')),
)

# ---------- CAPÍTULO 15 ----------
chapter('c15', 'Capítulo', '15', 'Tus tres primeros<br>contenidos',
        'Sin excusas: una presentación, una clase profunda y un experimento. Con eso ya tenés por dónde empezar.', [3],
        lead('Una pregunta que casi todos se hacen cuando ya entienden cómo crear contenido y qué contenido hacer es muy obvia: <b>¿cuáles son los primeros que debería crear?</b> Te propongo tres. Hay un millón de versiones posibles; esta es una base probada y fácil de adaptar.'),
        p('No son los únicos que podés hacer, ni tienen que ser exactamente así. Pero te dan una secuencia lógica, que muestra quién sos, enseña a fondo tu tema y te ayuda a descubrir qué disfrutás y qué disfruta tu audiencia. Y sobre todo, te sacan de la parálisis de “no sé por dónde empezar”.'),
        h3('1. Tu presentación'),
        p('Es el contenido donde contás tu historia junto con lecciones que tu audiencia puede aplicar de inmediato. Es importante aclarar qué <b>no</b> es: no es un video para presumir ni un resumen de tu currículum. Lo que sí es son entre tres y cinco momentos de tu carrera o tu vida que fueron puntos de inflexión, cada uno acompañado de una lección que tu audiencia pueda aprovechar.'),
        p('Eso es lo que lo hace valioso. No se trata solo de compartir lo que hiciste y dar credibilidad. Se trata de darle a tu audiencia valor útil, en forma de lecciones que aprendiste en el camino, tanto por hacer las cosas bien como por hacerlas mal. Un resumen de todos tus trabajos sería aburrido; las etapas más importantes, con una lección cada una, no.'),
        ol(['<b>Empezá con por qué estás creando contenido ahora.</b> ¿Cuál es el propósito de construir tu marca? Eso fija el marco.', '<b>Contá de tres a cinco momentos clave</b> de tu carrera o tu vida: puntos de inflexión que moldearon cómo pensás.',
            '<b>Emparejá cada momento con una lección clara</b> que tu audiencia pueda poner en práctica. Es lo que la mayoría de la gente pasa por alto.', '<b>Conectá cada lección con tu audiencia:</b> con sus dolores, sus metas, su etapa y su confusión.',
            '<b>Cerrá con lo que pueden esperar de vos:</b> para quién es tu contenido, cómo ayudás y, si querés, una primera señal de tu postura distinta.']),
        p('Fijate en esta idea: el video trata sobre vos, pero es para tu audiencia. Y un detalle más: asumí que nadie sabe quién sos. Aunque creas que ya te conocen, este es el momento de definir cómo querés que te perciban y de mostrar tus credenciales para el tema del que vas a hablar.'),
        h3('2. Tu clase profunda de posicionamiento'),
        p('En este contenido enseñás el tema por el que querés ser conocido, a través de tu postura distinta. No es una lista de consejos rápidos, ni una visión general superficial de tu sector, ni algo que esté de moda. Es una inmersión profunda y útil en tu tema principal. Es donde decís: “así veo yo este sector, de otra manera, y por esto te conviene”.'),
        p('Te recomiendo que dure al menos 25 minutos: una vez que entrás en el terreno de los 10 o 15 minutos, no alcanza para ir a fondo. No tiene que ser larguísimo: puede durar 30, 45 o 60 minutos, o más. Lo importante es que sea extremadamente útil.'),
        ul(['<b>Empezá con tu postura distinta</b> para que tu audiencia vea todo el resto desde esa perspectiva.', '<b>Definí el tema</b> por el que querés ser conocido, y definí con claridad los términos clave. Eso genera claridad inmediata.',
            '<b>Enseñá de tres a cinco ideas grandes</b>, no veinte superficiales. Un ejercicio útil: ¿qué pocas ideas me habrían cambiado todo si las hubiera entendido antes en mi carrera?', '<b>Facilitá los pasos para actuar.</b> Ahí es donde se construye la confianza: si tu audiencia actúa y logra el resultado, te va a asociar con alcanzar sus metas.',
            '<b>Cerrá estableciendo tu punto de vista</b> como su nueva forma de ver las cosas.']),
        p('Este contenido tiene otra ventaja práctica: se convierte en tu material madre. Cuanto más profundo sea, más fuente tendrás para ideas de contenido futuras, tuyas o de quien te ayude a producirlo.'),
        h3('3. Tu experimento'),
        p('Es una pieza pensada para probar algo completamente distinto, con un propósito claro: descubrir <b>qué disfrutás hacer</b> y <b>qué disfruta ver tu audiencia</b>. Si vas a hacer esto durante años, conviene que disfrutes los formatos que usás. Y a la vez, es la forma de enterarte de qué prefiere tu audiencia, más allá de lo que ya sabés.'),
        p('El experimento debe ser, de verdad, un experimento: en estilo, en formato y en enfoque. Incluso puede ser que tu forma de hablar sea un poco distinta. Algo que ayuda a pensar este paso: debería parecer, casi, un canal completamente distinto al de los dos primeros contenidos.'),
        chips(['Relato personal', 'Recorrido', 'Demostración', 'Historia guionada', 'Charla con giros', 'Entrevista', 'Producción creativa']),
        ol(['<b>Elegí un formato</b> que te dé curiosidad por probar.', '<b>Que sea muy distinto</b> de tus dos primeros contenidos.', '<b>Anclalo a una idea útil:</b> el valor sigue siendo educativo, aunque cambie el formato.',
            '<b>Al terminar, anotá cómo te sentiste</b> haciéndolo y cómo respondió tu audiencia.']),
        keybox('Cómo leer el resultado del experimento',
               table2('Si…', 'Entonces…', [('Te gustó y a tu audiencia también', 'Repetilo con más frecuencia: ganás los dos lados.'), ('Te gustó pero a la audiencia no', 'Repetilo de vez en cuando, lo suficiente para disfrutar sin aburrirla.'),
                                           ('No te gustó pero a la audiencia sí', 'Probá una versión más cómoda para vos del mismo formato.'), ('No te gustó y a la audiencia tampoco', 'Descartalo y probá otro experimento.')])),
        p('Fijate que esto parece contradictorio: seguir haciendo algo que disfrutás aunque a la audiencia no le guste tanto, pero a la vez prestar atención a cómo responde. En realidad es un equilibrio: los formatos que disfrutás son los que vas a poder sostener durante años, y los que le gustan a tu audiencia son los que te dan resultados. Idealmente encontrás los que cumplen las dos cosas.'),
        quote('Ya no tenés excusas para esperar la idea perfecta. Empezá con tu presentación.'),
        exercise('Tus tres guiones base',
                 p('En el workbook, escribí el esquema de tu presentación (los momentos clave y la lección de cada uno), el índice de tu clase profunda (de 3 a 5 ideas) y la idea de tu experimento.'),
                 p('No hace falta que esté perfecto: lo importante es empezar. Fijá una fecha para grabar el primero y anotala.')),
)

# ---------- CAPÍTULO 16 ----------
chapter('c16', 'Capítulo', '16', 'Producción y<br>preparación',
        'Poné fechas, preparate de verdad y aprendé de lo que publicás antes de seguir grabando.', [3],
        lead('Una cosa es saber qué publicar y otra es producirlo sin postergarlo. Estas son las lecciones de producción que más me repito a mí mismo, y que recomiendo aplicar desde el primer día.'),
        h3('Ponele fecha a todo lo grande'),
        p('Los proyectos grandes se postergan durante meses si no tienen una fecha límite. Es muy fácil decir “lo voy a hacer cuando tenga tiempo”. Cuando fijás la fecha de publicación primero y trabajás hacia atrás, transformás una buena idea en un proyecto real: reservás el lugar, organizás los recursos y avisás a quienes participan.'),
        p('Un proyecto enorme puede completarse en pocas semanas si hay una fecha clara y un compromiso con ella. Sin eso, probablemente tardes meses, y es posible que nunca lo termines.'),
        h3('Escribí, grabá y reescribí'),
        p('Es muy común que lo que escribiste suene distinto cuando lo decís en voz alta. Algunas líneas que se leen muy bien suenan raras al pronunciarlas. Por eso conviene ajustar el guion después de cada jornada de grabación, con lo que fuiste aprendiendo.'),
        p('Si a vos también te cuesta leer líneas completas frente a la cámara, usá puntos clave en lugar de guion completo, y escribí por completo solo la introducción, que es donde más se nota. Cada persona tiene una forma distinta de comunicarse: descubrir la tuya es parte del proceso.'),
        h3('No grabes de más antes de aprender'),
        p('Grabar en lote tiene ventajas, pero no conviene exagerar. El riesgo es la <b>falacia del costo hundido</b>: grabaste muchas piezas en un día, descubrís después que algo no funcionaba, y de todas maneras sentís que “ya que lo grabamos, lo publicamos todo”. Pero si lo que hiciste en esa sesión perjudica el resto del contenido, ¿por qué seguirías publicándolo?'),
        p('Por eso conviene usar lo que ya publicaste para decidir cómo vas a crear lo siguiente. Aprender del contenido publicado es parte del sistema. Y si estás muy motivado y querés grabar muchas piezas seguidas, aprovechalo, pero dejá espacio para ajustar.'),
        h3('Preparación: se ahorra en el set lo que se invierte antes'),
        case('El video corto que necesitó muchas horas',
             p('Alguien graba un video de diez minutos en exteriores sin una lista de planos. Todo se vuelve lento y confuso, y tiene que rehacerlo otro día. La segunda vez dedica varias horas a preparar cada plano: busca los lugares en un mapa, define cuál es la toma de cada uno y qué va a decir en cada punto.'),
             learn('Dedicar varias horas a preparar un video corto es normal. <b>La preparación es lo que hace rápida la grabación.</b>')),
        ul(['<b>Lista de planos:</b> plano por plano, qué se ve, dónde y qué se dice.', '<b>Lugares definidos de antemano:</b> mirá fotos o mapas para decidir dónde vas a grabar.', '<b>Un plan B:</b> pensá qué harías si el lugar o la luz no son los esperados.', '<b>Una prueba corta:</b> grabá unos segundos antes de seguir, para revisar imagen y sonido.']),
        h3('Si vas a grabar en lugares públicos'),
        p('Grabar frente a otras personas incomoda a mucha gente. Es normal, y a muchos nos pasa. Algunas ideas que ayudan:'),
        ul(['<b>Usá lentes de sol</b> si te incomoda que te miren: ayudan a ignorar a los demás.', '<b>Concentrate en lo que estás haciendo.</b> La mayoría de la gente te mira un segundo y sigue con su día.',
            '<b>Simplificá el equipo</b> y usá ajustes automáticos para entrar y salir rápido. Cuanto menos tenés que ajustar, menos te frena.', '<b>Pedí permiso</b> cuando haga falta y respetá a las personas y al lugar.', '<b>Sé amable con quien te recibe.</b> Un lugar puede permitirte grabar una vez y pedirte que no vuelvas.']),
        p('Con práctica, grabar en público se vuelve mucho más natural. Y vas a notar que las personas que viste mirándote ya están pensando en otra cosa segundos después.'),
        h3('Un flujo de revisión que evita mil correcciones'),
        p('Si trabajás con alguien que edita o diseña, esta forma de trabajar evita vueltas interminables. Mucha gente termina en versiones 5, 6 y 7 de un mismo contenido porque el feedback llega de a pedazos.'),
        ol(['<b>Hacé primero una versión base</b> del corte (con la parte principal del contenido ya armada), para que la revisen antes de embellecerla.', '<b>Dejá tus notas directamente sobre cada imagen</b>, con dibujos o referencias si hace falta: “acá imagino algo así”.',
            '<b>Entregá todo junto</b>, con las notas ya organizadas y los archivos listos. Cuanto más claro, menos preguntas.', '<b>Revisá con calma, no veinte veces.</b> Una revisión buena vale más que muchas apuradas.']),
        p('Y un detalle de proceso: si grabaste varias piezas con diferentes escenas o ropas, podés usarlas después para sacar clips y distribuirlos con más facilidad. Cambiar de escenario también ayuda a mantener fresca la energía.'),
        exercise('Tu fecha y tu preparación',
                 p('Elegí tu próximo contenido. Escribí su fecha de publicación. Anotá cuántas horas de preparación necesita y qué tenés que tener listo antes de grabar.'),
                 p('Si es un video, hacé una lista de planos. Si es otro formato, escribí los pasos de preparación. Definí además el flujo de revisión que vas a usar.')),
)

# ---------- CAPÍTULO 17 ----------
chapter('c17', 'Capítulo', '17', 'Equipo, delegación<br>y demanda',
        'A medida que crece, necesitás ayuda. Delegar bien es una habilidad, y no incluye regalar tu voz.', [3],
        lead('Cuando tu marca empieza a funcionar aparece un problema nuevo: tenés más demanda que tiempo. La respuesta es <b>pedir ayuda</b>, pero de la manera correcta.'),
        p('Casi nadie te cuenta esta parte. Al principio hacés todo vos. Después tu contenido empieza a funcionar, recibís mensajes, consultas y solicitudes, y tu agenda se llena. Si no organizás cómo vas a atender todo eso, empezás a perder oportunidades y a quemarte. Este capítulo trata de cómo crecer sin perder el control ni tu voz.'),
        h3('Contratá bien y confiá'),
        p('Cuando contrates a alguien para tareas creativas (edición, diseño, motion, redacción), pedile un portafolio que muestre que es bueno en lo que hace. Parece obvio, pero es una condición. Y si el portafolio lo demuestra, <b>confiá</b>. Si contratás a alguien y le decís exactamente qué hacer, en el mundo creativo estás perdiendo el sentido de contratar: estás contratando a un robot, no a un colaborador.'),
        p('Una buena práctica es decirle claramente: “quiero que muestres tus fortalezas y lo que te parece distinto de lo que hacen otros”. Muchas veces los mejores resultados vienen de un profesional cuyo portafolio incluye cosas muy distintas a tu proyecto, porque trae un ángulo diferente.'),
        h3('Cómo dar tus notas'),
        ul(['<b>Separá lo imprescindible de lo que es preferencia.</b> Decí explícitamente cuáles son los cambios innegociables y cuáles son gustos tuyos que estás dispuesto a discutir.', '<b>Preguntá más de lo que ordenás.</b> “¿Qué pensás si hacemos esto acá?” abre la conversación.',
            '<b>Incluí al equipo en decisiones creativas.</b> Consultales cuando haya dudas sobre un contenido.', '<b>Escuchá los argumentos.</b> Si alguien defiende una idea con buenas razones, tenerlo en cuenta construye confianza y mejora el resultado.']),
        p('Algo que he visto una y otra vez: si contratás a las personas adecuadas y les das ese nivel de confianza, suelen elevarse por encima del nivel al que las trataste. No lo pienses como una concesión: es la forma de conseguir lo mejor de cada persona.'),
        h3('Delegar en tres pasos'),
        p('Delegar no es entregar una tarea y desaparecer. Es una secuencia en la que primero enseñás, después acompañás y finalmente soltás.'),
        formula(['Lo hacés vos', 'Lo hacen juntos', 'Lo hace la otra persona y vos observás'], 'Cómo se delega sin perder tu voz'),
        ol(['<b>Demostrás:</b> hacés la tarea vos, explicando tus decisiones.', '<b>Duplican:</b> la hacen juntos, y la otra persona empieza a proponer.', '<b>Delegás:</b> la hace la otra persona y vos observás y ajustás.']),
        h3('No tercerices tu voz'),
        p('Hay un error muy común: pensar que al contratar a alguien de contenido, esa persona va a escribirlo todo y hacer que todo suceda por arte de magia. Aunque conozca muy bien tu trabajo, necesita una etapa de <b>calibración</b>, en la que aprende tu gusto, tus ideas y tu forma de hablar. Si saltás esa etapa, lo que obtenés es una versión tercerizada de vos, no tu verdadera voz.'),
        p('Lo digo con todo respeto por quienes trabajan detrás de alguien: si tu equipo pudiera escribir este contenido tan bien como vos, entonces esa persona sería la que está frente a la cámara. En algún momento puede pasar, y eso es parte del crecimiento. Pero mientras tanto, el contenido tiene que seguir saliendo de vos en algún nivel.'),
        quote('Si alguien de tu equipo pudiera escribir esto igual que vos, esa persona sería la que sale en cámara.'),
        p('Y es más lento de lo que muchos quisieran. En los primeros meses probablemente escribas vos. Después empiezan a escribir juntos. Más tarde la otra persona prepara un borrador avanzado y vos lo terminás. Cada etapa requiere paciencia, y todas son necesarias.'),
        h3('Cuando llega la demanda'),
        p('Si tu contenido empieza a funcionar y recibís muchos pedidos de personas que quieren trabajar con vos, vas a necesitar ordenar la operación. No solo la de tu marca: también la del negocio. Antes eras alguien con un buen trabajo que usaba el contenido para conseguir más trabajo. Ahora tenés algo que se parece más a una empresa.'),
        p('En ese momento suele hacer falta alguien que te ayude a organizar la agenda, las respuestas y el seguimiento. Y a veces conviene pensar más allá de una persona de apoyo: alguien que ayude con las operaciones del negocio, no solo de tu vida diaria.'),
        case('Una guía gratuita que llena la agenda',
             p('Un asesor ofrece una guía gratuita a cambio del correo electrónico. En unos meses su lista crece y recibe más consultas de las que puede atender. Decide contratar a alguien que filtre las consultas y agende las reuniones, y reserva su propio tiempo para las conversaciones importantes.'),
             learn('Crecer también implica <b>ordenar el negocio</b>, no solo publicar.')),
        h3('Cuidado con las demasiadas voces'),
        p('Cuando empieza a ir bien, aparece mucha gente con ganas de ayudarte: conocidos, colegas, personas que te respetan. Todos te dan consejos con muy buena intención, pero muchos son contradictorios. Tantas voces con tantas ideas distintas pueden dejarte paralizado. Lo ideal es agradecer cada consejo, pero decidir a partir de tus propios objetivos, el mapa inverso del capítulo 1 y lo que dicen tus clientes.'),
        exercise('Tu plan de apoyo',
                 p('Anotá qué tareas te quitan tiempo y no necesitan tu voz (edición, organización, agenda, seguimiento). Elegí una para delegar primero.'),
                 p('Escribí cómo la vas a delegar en los tres pasos: la hacés vos, la hacen juntos, la hace esa persona. Definí qué vas a mirar para saber que la calibración funcionó.')),
)

# ---------- CONCLUSIÓN ----------
chapter('concl', 'Conclusión', None, 'Empezá con<br>lo que tenés',
        'No necesitás ser famoso ni tener una gran audiencia. Necesitás claridad, constancia y confianza.', [0, 1, 2, 3],
        lead('Al comienzo de este libro te planteé una decisión: construir una marca personal para conseguir seguidores o para conseguir <b>clientes</b>. Si llegaste hasta acá, ya sabés cuál elegís.'),
        p('Recorrimos un camino completo. Definiste un resultado y un mapa inverso. Te ubicaste como estudiante o como experto. Pensaste en una marca que puedas sostener. Escuchaste a tu cliente y su problema. Encontraste tu postura distinta y la resumiste en una frase. Entendiste cómo se construye una marca, qué es la confianza y cómo hablarle a quien todavía no te conoce. Y armaste un sistema que se adapta a tu vida.'),
        formula(['Resultado', 'Postura', 'Confianza', 'Constancia'], 'El recorrido en una línea'),
        p('Quiero recordarte lo más importante de todo el libro, en pocas ideas:'),
        ol(['Antes de crear contenido, definí qué querés lograr y si el contenido público te acerca a eso.', 'Sé honesto sobre tu punto de partida: si sos estudiante, sé estudiante.', 'Construí una marca que no odies, porque la que odies la vas a abandonar.',
            'Optimizá para tus clientes, no para tus competidores ni para tus seguidores.', 'Encontrá tu postura distinta y repetila hasta que tu audiencia la diga por vos.', 'Priorizá la confianza sobre el alcance cuando tu oferta es de alto valor.',
            'Hacé cada contenido como si te estuvieran conociendo por primera vez.', 'Armá un sistema que puedas sostener: constancia antes que intensidad.']),
        p('Nada de esto es magia. Es repetición, aprendizaje y ajuste. No necesitás hacerlo perfecto. Necesitás empezar con una versión pequeña, mirar qué pasa y mejorarla. Quienes obtienen resultados no son los que tienen la mejor idea el primer día, sino los que siguen publicando, escuchando y ajustando cuando los demás ya abandonaron.'),
        '<div class="manifesto"><div class="mcol"><div class="mh">Empezá con lo que tenés</div><div>Un teléfono.</div><div>Una experiencia.</div><div>Un problema que sabés resolver.</div><div>Una persona a la que podés ayudar.</div></div>'
        '<div class="mcol"><div class="mh">Después</div><div>Publicá.</div><div>Escuchá.</div><div>Ajustá.</div><div>Volvé a publicar.</div></div></div>',
        quote('Tu marca personal no es un personaje. Es una selección intencional de lo que querés que el mundo asocie con vos.'),
        p('Gracias por haber llegado hasta acá. El workbook, el plan de 30 días y la biblioteca de ganchos que siguen son para que conviertas todo esto en acción. Imprimilos, completalos y volvé a ellos cada mes.'),
        p('Y si tenés que quedarte con una sola idea, que sea esta: tu objetivo no es que todo el mundo te conozca. Es que, cuando aparezca el problema correcto frente a la persona correcta, <b>tu nombre sea una de las opciones que recuerde</b>. <b>Empezá hoy.</b>'),
        with_action=False,
)
