# ---------- CAPÍTULO 10 ----------
chapter('c10', 'Capítulo', '10', 'Tu forma de presentar<br>y tu empaque',
        'Dos palancas que se suman a tu postura: cómo comunicás y cómo envolvés lo que comunicás.', [2],
        lead('Además de tener algo valioso para decir, importa <b>cómo lo decís</b> y <b>cómo lo presentás</b>. Son las otras dos palancas para destacar: la segunda más fuerte es tu forma de presentar, y la tercera es tu empaque.'),
        p('En el capítulo 5 vimos que la postura distinta es la palanca más fuerte. Pero una postura distinta solo sirve si la gente llega a escucharla, y si cuando llega, la entiende. Ahí entran estas dos palancas. Una trabaja <i>durante</i> el contenido (tu forma de presentar). La otra trabaja <i>antes</i> de que alguien lo abra (tu empaque).'),
        h3('Tu forma de presentar'),
        p('Mucha gente arruina su forma de presentar porque cree que tiene que convertirse en una versión exagerada de sí misma frente a la cámara. Es un consejo que se repite mucho: “hacé lo que harías normalmente, pero diez veces más, porque en cámara se ve diferente”. Si ese es tu estilo y estás construyendo intencionalmente un personaje, es una decisión válida. Pero mi recomendación es la contraria: que sea la versión más auténtica de quién sos.'),
        p('Presentar no es actuar. Es <b>quitar todo lo que te frena y te impide ser vos</b>. Si sos tranquilo, sé tranquilo. Si sos intenso al enseñar, sé intenso. Si sos seco y con humor irónico, traé ese humor a tu contenido. Debe ser un reflejo natural de cómo te comunicás en tu vida cotidiana.'),
        p('Cuando intentás copiar la energía de tu creador favorito, terminás siendo una versión genérica de esa persona. Y terminás agotado, porque construiste un personaje y no una marca personal. Un personaje requiere esfuerzo todos los días. Tu forma natural de ser no.'),
        quote('No necesitás ser la persona más carismática. Necesitás ser la más útil.'),
        p('Si optimizás tu marca alrededor de la utilidad, construís una marca fuerte, aunque no sea la audiencia más grande: va a ser una audiencia de personas que confían profundamente en vos. Si optimizás alrededor del carisma por encima de la utilidad, construís una marca basada en la vanidad.'),
        h3('Entender bien tu idea es la mitad del trabajo'),
        p('Muchas veces lo que nos cuesta no es la forma de comunicar sino que no entendemos del todo el punto que queremos transmitir. Cuanto mejor entiendas lo que querés decir, mejor lo vas a transmitir, sin importar si sos tímido o extrovertido.'),
        keybox('Una prueba para saber si entendés tu propia idea',
               p('Probá explicar la misma idea a tres personas distintas, en tres situaciones completamente diferentes: por ejemplo, a un experto, a un principiante y a un niño. Si podés hacerlo con claridad, entendés el concepto lo suficiente como para comunicarlo a tu audiencia de una manera que realmente entiendan.')),
        h3('Revisá tus grabaciones como un deportista'),
        p('Un hábito que me parece muy útil: revisar tus propias grabaciones, como hace un jugador con los partidos que jugó. Mirá qué quedó claro y qué no, dónde diste demasiadas vueltas, cuánto tardaste en llegar al punto importante y cómo podrías haberlo dicho de forma más breve.'),
        p('Es especialmente útil si sos una persona que piensa mientras habla: a veces tardás más de lo necesario en llegar a una idea. Cuando lo notes, pausá la grabación y pensá cómo responderías esa misma pregunta de manera más clara y concisa. Con la práctica, ese es el tipo de mejora que más se nota.'),
        h3('Tu empaque'),
        p('Es muy común escuchar “este contenido era buenísimo, ¿por qué nadie lo vio?”. Muchas veces el contenido era bueno, pero no tenía un empaque que invitara a abrirlo. No competís solo con otros de tu sector: competís con todo lo que aparece en la pantalla de esa persona, incluidos los creadores que más admira.'),
        p('El empaque es la única ventaja competitiva que tenés antes del clic. Tu postura distinta y tu forma de presentar solo pueden compartirse y generar conexión <b>después</b> de que alguien hace clic. El empaque es lo que consigue ese clic.'),
        deflist([('Título y miniatura', 'Lo primero que ve alguien antes de decidir si entra. Tienen que prometer algo concreto y relevante.'),
                 ('Gancho', 'La primera frase o imagen del contenido, que le dice “esto es para vos”.'),
                 ('Formato', 'La manera en que está hecho: hablar a cámara, grabar en exteriores, mostrar una pantalla, contar una historia, hacer una demostración.')]),
        p('Un ejemplo: podés tener dos piezas sobre el mismo tema con formatos completamente distintos, una hablando a cámara y otra grabada en un recorrido, y cada una atrae a personas distintas y funciona mejor en ocasiones distintas. El mismo contenido, empacado de otra manera, tiene otro resultado.'),
        h3('Tu biblioteca de empaques'),
        p('Cuando más cuesta pensar un buen empaque es justo cuando lo necesitás: con el contenido ya grabado y editado, tratando de decidir cómo presentarlo. Por eso conviene tener una biblioteca de inspiración lista para consultar. Pensalo como un armario de papeles de regalo: cuando tenés que envolver un regalo, abrís el armario y elegís el que mejor le queda.'),
        ol(['<b>Guardá capturas</b> de títulos, miniaturas, ganchos y formatos que te llamen la atención. Esas capturas que ahora se pierden en tu galería pueden volverse material de trabajo.', '<b>Organizalas</b> en un documento o carpeta al que puedas volver fácilmente, por plataforma o por tipo.',
            '<b>Navegá sin buscar nada específico</b>, de forma periódica (semanal, quincenal o mensual). Cuando algo te llame la atención, guardalo.', '<b>Guardá también lo absurdo</b>, lo que no sabés cómo adaptar. Con el tiempo, una parte importante resulta útil cuando aparece la combinación correcta de problema y solución.']),
        p('Lo mismo vale para cualquier plataforma: publicaciones escritas con buen rendimiento, carruseles, videos cortos. Podés guardar ejemplos en carpetas dentro de la propia plataforma, y consultarlos cuando tengas que presentar una idea. Cuando tengas cientos de ejemplos de cómo luce un buen contenido en cada plataforma, vas a poder adaptar tu mensaje a cada una con mucha más facilidad.'),
        h3('Mirá fuera de tu sector'),
        p('Hay un problema que se repite en todos los sectores: todos se copian entre sí, y todos terminan viéndose igual. Si no querés verte igual, no hagas lo que todos hacen. Es obvio, pero casi nadie lo hace.'),
        p('Una forma muy efectiva de evitarlo es mirar otros sectores y nichos. Observá qué les funciona a creadores de mundos completamente diferentes y preguntate qué elemento podrías tomar prestado desde los principios básicos. Eso te va a hacer destacar frente a tus competidores, incluso si compartís temas y consejos parecidos.'),
        case('La coach que miró otro mundo',
             p('Imaginá a una coach de carrera que revisa canales de jardinería, cocina y bricolaje para aprender cómo presentan un proceso paso a paso. Adapta un formato de “antes y después” a su propio tema: una revisión de currículums.'),
             learn('Todos se copian dentro de su propio nicho, así que <b>mirar otro nicho te hace diferente</b>.')),
        exercise('Tu biblioteca de empaques',
                 p('Creá hoy una carpeta de inspiración. Durante esta semana guardá al menos 20 ejemplos de títulos, miniaturas, ganchos o formatos que te llamen la atención, incluidos algunos de sectores que no tienen nada que ver con el tuyo.'),
                 p('Después marcá tres que podrías adaptar a tu propio tema y escribí cómo lo harías. Programá un momento fijo cada semana o cada mes para seguir agregando ejemplos.')),
)

# ---------- CAPÍTULO 11 ----------
chapter('c11', 'Capítulo', '11', 'Tres capas de contenido<br>y cómo estructurarlo',
        'No es profundo o amplio: necesitás una mezcla, más un toque personal. Y cada pieza necesita una apertura clara.', [2],
        lead('En internet se discute mucho si conviene crear contenido profundo o contenido general. Mi respuesta es que no es una cosa o la otra. Y falta un ingrediente en esa discusión: <b>lo personal</b>.'),
        p('Mucha gente te dice que te inclines por una sola opción, y se enoja si no estás de acuerdo. Pero como cualquier cosa en la vida, hay matices. Necesitás una buena proporción de ambos tipos de contenido. Y como estás construyendo una marca <i>personal</i>, necesitás una tercera capa: la que muestra a la persona detrás.'),
        p('Te propongo pensarlo en tres capas. Más que una regla, es un punto de partida que podés ajustar según tu caso y según el momento.'),
        deflist([('Capa 1: profundo', 'Es tu plato principal. Resuelve problemas complejos de tu cliente ideal con marcos de trabajo, tácticas y tu postura distinta. Suele ocupar alrededor de tres cuartas partes de tu contenido.'),
                 ('Capa 2: amplio dentro del nicho', 'Es la guarnición. Subtemas que siguen sirviendo a tu cliente ideal pero llegan a una base más amplia. Suele ocupar alrededor de una quinta parte.'),
                 ('Capa 3: personal', 'Es el postre. Muestra a la persona detrás de la marca: gustos, historias, valores. Una porción pequeña, repartida dentro del resto.')]),
        note('estas proporciones son una guía flexible, no una regla. No seas literal: adaptalas a tu caso y a cada momento, y vas a ver que cambian de un mes a otro.'),
        h3('Capa 1: el contenido profundo'),
        p('Es la principal fuente de valor de tu marca. Acá van los marcos de trabajo, los problemas dolorosos que resolvés, los consejos tácticos y los cambios de creencia o de punto de vista que proponés sobre tu sector. Es el contenido que genera la mayor confianza en tu capacidad de obtener resultados y refuerza tu credibilidad. Y suele ser el que atrae a los clientes que mejor pagan, porque aumenta las probabilidades de que crean que realmente podés ayudarlos a resolver su problema.'),
        h3('Capa 2: el contenido amplio dentro del nicho'),
        p('Son los subtemas que siguen sirviendo a tu cliente ideal, pero que llegan a una base más amplia de personas. La clave es que, a diferencia del contenido general y aleatorio, <b>sigue atrayendo a personas interesadas en el tema general</b> que tratás. Eso aumenta las probabilidades de que quien llegue tenga algún interés en tu oferta.'),
        case('Una capa por cada tipo',
             p('Imaginá a una asesora de negocios que publica: <b>Profundo:</b> cómo diseñar una oferta clara y fijar precio. <b>Amplio dentro del nicho:</b> cómo aprovechar las relaciones que ya tenés para conseguir clientes (puede interesar a cualquier persona que quiera retomar contacto con viejos colegas). <b>Personal:</b> cuenta cómo organiza su semana de trabajo y menciona de pasada su pasión por la cerámica.'),
             learn('Todo apunta al mismo tipo de persona, pero <b>cada capa cumple una función distinta</b>.')),
        h3('Capa 3: el contenido personal'),
        p('Esta capa es la que más se olvida y la que más te puede diferenciar. Lo más probable es que, sobre el tema que elegiste, haya otras personas hablando. Probablemente incluso enseñen principios parecidos, y hasta puede que tengan posturas similares. Pero lo que no pueden replicar es la combinación única de tus intereses, tus preferencias, tus pasatiempos y tus pasiones, que te hacen el ser humano que sos.'),
        p('Y un detalle importante: <b>no hace falta dedicarle piezas enteras</b>. No estoy hablando de contenido tipo “mirá mi estilo de vida”. El 5% personal no significa que un contenido de cada veinte tenga que ser sobre tus aficiones. Está mejor repartido dentro del resto: una referencia en un video, una anécdota en una publicación, un objeto en el fondo de la imagen.'),
        p('¿Por qué importa? Porque cuantos más intereses compartas, más oportunidades tiene tu audiencia de conectar con vos. Cuanto más cercana es una relación, más intereses en común suelen tener las dos personas. Si querés desarrollar una relación cercana con tu audiencia, tienen que poder descubrir en qué más se parecen a vos, aparte del tema principal.'),
        h3('Cómo estructurar cada pieza'),
        p('Ya sabés qué tipo de contenido vas a crear. Ahora hay que ordenarlo para que a tu audiencia le resulte fácil consumirlo, aprender y actuar. En este punto hay muchísimos consejos sobre “trucos de retención”: gráficos que cambian cada pocos segundos, cambios de escena constantes, elementos nuevos en pantalla.'),
        p('Mi observación es que casi todos esos trucos provienen del contenido de <b>entretenimiento</b>, no del educativo. En contenido educativo tu objetivo es que la audiencia actúe en base a lo que decís. Si tenés constantemente gráficos que distraen del mensaje principal, le dificultás aprender. En contenido educativo, el mayor truco de retención es que tu audiencia <b>aprenda</b>.'),
        h3('El primer aprendizaje llega rápido'),
        p('Durante años se repitió una idea: enterrar el valor al final para que la gente se quede. Funcionó durante mucho tiempo. Pero hoy se produce tanto contenido que la gente ya no tiene paciencia para esperar. Y esa es la palabra clave: la capacidad de atención de las personas no es realmente una capacidad, es un nivel de <b>paciencia</b>. Están menos dispuestas a esperar valor de vos porque saben que otro creador se lo puede dar más rápido.'),
        p('Pensá en cómo funciona con un servicio: si aprendo algo valioso en los primeros sesenta segundos de un contenido, asumo que voy a seguir aprendiendo y me quedo. Es una suposición basada en mi experiencia con otros contenidos. Por eso conviene llevar a tu audiencia a un primer aprendizaje lo antes posible. No hace falta que sea el mayor, solo que sea útil.'),
        keybox('Una apertura en cuatro pasos',
               ol(['<b>Para quién es:</b> dejá claro a quién le habla este contenido. Si el título y la miniatura ya lo dicen, no hace falta repetirlo.', '<b>Por qué yo:</b> tu credibilidad para este tema específico.',
                   '<b>Hacia dónde vamos:</b> un mapa corto de lo que van a lograr, desde el problema que tienen hasta la solución que buscan.', '<b>Primer aprendizaje:</b> un dato valioso y útil, cuanto antes.'])),
        h3('El resto de la pieza'),
        p('Después de la apertura, tenés una estructura base muy simple. Se puede hacer mucho más compleja, pero esta alcanza para empezar y para que no te quedes mirando una página en blanco sin saber por dónde arrancar.'),
        formula(['Contexto', 'Un principio', 'Una historia', 'La acción', 'Un ejemplo', 'Siguiente contenido'], 'Estructura base de una pieza'),
        ul(['<b>Contexto:</b> de qué vas a hablar y por qué importa.', '<b>Un principio:</b> la idea central que querés que se lleven.', '<b>Una historia:</b> un caso real o ilustrativo que muestre ese principio en la vida.',
            '<b>La acción:</b> qué tiene que hacer tu audiencia con esa idea.', '<b>Un ejemplo:</b> cómo se ve hacerlo bien, mal o ambas cosas.', '<b>Siguiente contenido:</b> invitá a ver o leer lo que sigue.']),
        exercise('Tu primera estructura',
                 p('Elegí uno de tus problemas del capítulo 4 y escribí su apertura en los cuatro pasos y su estructura base en una hoja.'),
                 p('Contalo en voz alta a alguien y fijate si el primer aprendizaje llega en el primer minuto. Además, anotá qué pieza de cada capa (profunda, amplia y personal) publicarías esta semana.')),
)

# ---------- CAPÍTULO 12 ----------
chapter('c12', 'Capítulo', '12', 'Tu capacidad, tu medio<br>y tus plataformas',
        'Un sistema sostenible parte de tu tiempo, tu energía y lo que te resulta natural, no de copiar a otros.', [3],
        lead('Casi todo lo que viste hasta acá se puede perder si no armás un sistema que puedas sostener. <b>La constancia le gana a la intensidad.</b>'),
        p('Probablemente hayas escuchado que una gran mayoría de las personas que empiezan a crear contenido lo abandonan durante el primer año. Toda la inversión, las incomodidades de exponerse en público y el trabajo, a la basura. Por eso esta parte del libro es tan importante: se trata de que sigas en esto el tiempo suficiente para obtener resultados.'),
        p('Y hay un error que se repite mucho: intentar copiar lo que hace tu creador favorito, o replicar lo que te dice el gurú de tu red social: estar en todas las plataformas a la vez, publicar muchas veces por día. Eso no solo es insostenible, sino que suele ser una bomba de tiempo que termina en abandono.'),
        h3('Partí de tu realidad'),
        p('Construir un sistema sostenible significa que tu estrategia de contenido tiene que ajustarse a las limitaciones reales de tu negocio, tu vida y tu nivel de experiencia. No hablo de algo místico: hablo de tiempo, de capacidad de energía, de capacidad mental y de práctica acumulada.'),
        p('Una persona puede tener una o dos horas a la semana para dedicar al contenido. Otra puede tener diez. Las dos pueden armar un excelente sistema, pero no el mismo. Y lo mismo con la experiencia: alguien que nunca se grabó no puede arrancar con un video por semana. Tiene que ir adaptándose poco a poco.'),
        keybox('Preguntas para conocer tu capacidad real',
               ul(['¿Cuántas horas por semana tengo realmente para el contenido?', '¿Qué partes del proceso me dan energía y cuáles me la quitan?', '¿A qué hora del día estoy más lúcido y me comunico mejor?',
                   '¿Qué nivel de experiencia tengo frente a la cámara o al micrófono?', '¿Qué otras responsabilidades tengo que cuidar mientras construyo mi marca?'])),
        p('Con estas respuestas podés hacer una ingeniería inversa de tu sistema: partís de tu tiempo y tu energía, y a partir de ahí diseñás cuánto y cuándo producir, en vez de intentar mantener un ritmo que no es el tuyo. Por ejemplo, si rendís mejor por la mañana, organizá las grabaciones en ese horario.'),
        quote('Dar un paseo de veinte minutos todos los días durante años rinde más que entrenar a fondo seis meses y abandonar.'),
        p('Lo mismo ocurre con tu estrategia: si publicás con poco volumen pero de manera constante durante muchos años, vas a superar a quien fue a toda velocidad durante un año y se quemó.'),
        h3('Tu estrategia tiene que complementar tu negocio'),
        p('Esto es lo que te diferencia de un creador promedio: vos tenés un negocio que gestionar. Tu sistema de contenido tiene que complementar cómo es tu negocio y tu día a día, no ser un molde en el que intentás forzar algo que no encaja. Si no lo hacés bien, tu marca personal y tu negocio terminan compitiendo entre sí por tu tiempo, cuando deberían ser complementarios.'),
        p('Hay muchas formas de organizarlo. Algunas personas ocupadísimas apenas tienen unos minutos por semana para el contenido específico de una plataforma, y el resto lo resuelven documentando su trabajo cotidiano. Otras reservan una jornada completa cada tanto para grabar. No importa lo que hagan los demás: importa cómo es tu día a día.'),
        h3('Elegí tu medio'),
        p('Hay cuatro medios posibles para comunicar: video, audio, texto y gráficos. En lugar de elegir el que usan todos tus referentes o el que está de moda, elegí el que te resulte más natural para comunicar tus ideas y quién sos de la manera más auténtica posible.'),
        table2('Si lo tuyo es…', 'Podés empezar por…', [('Hablar frente a una cámara', 'Video: es el medio con más posibilidades de aprovechamiento después (clips, audio, texto).'),
                                                         ('Hablar, pero te incomoda la cámara', 'Audio o podcast, y sumar video más adelante.'),
                                                         ('Escribir', 'Un boletín o artículos largos antes que videos, sobre todo si estar en cámara te incomoda.'),
                                                         ('Diseñar o explicar visualmente', 'Gráficos y carruseles, con mensajes breves y claros.')]),
        p('Es cierto que el video es el más completo: de un video podés sacar clips cortos, tomar el audio para un podcast y usar la transcripción para escribir publicaciones y correos. Pero si el video te aterra, probablemente no te vas a mantener, y es posible que ni siquiera empieces. Elegí algo con lo que puedas generar impulso y dejá que ese impulso te guíe hacia el siguiente medio.'),
        h3('Elegí tus plataformas'),
        p('Mucha gente entiende mal el consejo de “dominar todas las plataformas”. Para quien está empezando es una estrategia terrible. Intentar estar en todas partes a la vez suele terminar en contenido flojo. Es como decidir que vas a empezar a escalar montañas y que tu primera salida será una de las más difíciles del mundo.'),
        compare('Si trabajás solo', ['Una plataforma principal, donde ponés tu energía y tus ideas nuevas: es el plato principal.', 'Una plataforma secundaria, donde reutilizás el contenido de la principal.', 'Crear contenido pilar para la principal y adaptarlo a la secundaria.'],
                'Si tenés equipo', ['Tres plataformas principales.', 'El foco de innovación rota entre ellas, de a una por vez.', 'Las otras dos quedan en modo de mantenimiento, publicando formatos que ya sabés que funcionan.']),
        p('La plataforma principal recibe tu energía, tu innovación y tu atención. La secundaria recibe contenido reutilizado. No es que no te importe: es que no dedicás tu energía a innovar en ella, la reservás para la principal. Cuando sientas que tu plataforma principal está afinada, pasás el foco a otra, y después a otra. Al terminar el ciclo, volvés a la primera, porque probablemente tu audiencia ya esté lista para algo nuevo.'),
        h3('Cómo elegir las plataformas'),
        ol(['<b>Mirá tu medio:</b> las plataformas prefieren distintos formatos. Si elegiste escribir, quizás una plataforma de video no sea tu mejor opción ahora.', '<b>Preguntate dónde pasa más tiempo tu cliente ideal.</b>',
            '<b>Si no lo sabés, preguntalo.</b> Encontrá a alguien que se parezca a tu cliente ideal y preguntale. No es tan complicado.', '<b>No lo conviertas en excusa:</b> si estás dándole demasiadas vueltas, probablemente lo estés usando como una forma de procrastinar. Elegí una y empezá. Podés cambiar después.']),
        exercise('Tu capacidad y tus plataformas',
                 p('En el workbook, respondé las preguntas de capacidad. Después elegí tu medio, tu plataforma principal y tu plataforma secundaria (o tus tres, si tenés equipo).'),
                 p('Anotá por qué elegiste cada una. Y escribí cuál será tu horario de creación semanal, teniendo en cuenta tu momento del día más lúcido.')),
)

# ---------- CAPÍTULO 13 ----------
chapter('c13', 'Capítulo', '13', 'Ritmo y mejora<br>continua',
        'Empezá con un ritmo que puedas sostener y aprendé de lo que publicás. Subir es fácil, bajar casi nunca.', [3],
        lead('Aunque elijas bien tus plataformas, podés arruinarlo con un ritmo de publicación que no puedas sostener. Ser disciplinado con la cadencia es tan importante como ser disciplinado con la plataforma.'),
        p('No conviene copiar el ritmo de tu creador favorito si él tiene un equipo de treinta personas y vos estás solo. Por más cliché y repetido que suene, <b>esto es una maratón, no una carrera de velocidad</b>. Y hay una razón práctica: siempre podés aumentar el volumen de lo que publicás, pero lo que he visto es que a los creadores les cuesta muchísimo reducirlo. Una vez que establecés una expectativa con tu audiencia, retroceder es difícil.'),
        p('Pensá en los creadores que durante tres o cuatro años tuvieron sus quince minutos de fama: se volvieron virales y desaparecieron. ¿Cuánto les quedó de ese sprint? Hay excepciones, pero en general es un periodo muy corto que no dura. Lo que querés construir es un sistema que te permita seguir cosechando los beneficios de una marca fuerte año tras año, con contenido que se acumula en interés con el tiempo.'),
        h3('Construí para tu yo del futuro'),
        p('Tu capacidad de hoy no es la que vas a tener dentro de un año. Si tu marca funciona, tu negocio va a crecer y vas a tener menos tiempo para el contenido. Por eso conviene diseñar tu ritmo de publicación en función del tiempo que vas a tener, no del que tenés hoy. Si empezás con un video por semana y a los cuatro meses no podés sostenerlo, tu marca se resiente justo cuando más lo necesitás.'),
        keybox('Cuánto publicar',
               p('No te voy a dar un número exacto, porque cada persona es distinta. Empezá con una frecuencia que te parezca manejable. Si te propongo dos veces por semana y te suena a “mucho”, no lo hagas. Pasá a una por semana. Y si eso también te suena a mucho, a una cada dos semanas, o una por mes.')),
        p('Lo importante no es con qué frecuencia empezás, sino <b>cada cuánto aumentás ese ritmo</b>. Mientras sepas que podés subir el volumen cada cierto tiempo, ya estás listo. Aunque en tu primer año publiques solo una pieza larga por mes, en el segundo podés aumentar si querés, y no vas a tener problema, porque estás corriendo una maratón.'),
        h3('Método de ensayo y foco'),
        p('Una forma simple de saber qué quiere tu audiencia es alternar dos momentos, que funcionan como un acordeón que se abre y se cierra.'),
        deflist([('Ensayo', 'Al principio publicás con más volumen. Usás la cantidad para aprender qué considera valioso tu audiencia. Es un momento de exploración.'),
                 ('Foco', 'Con lo que aprendiste, ponés el mismo esfuerzo que antes dedicabas al volumen en menos piezas, todas parecidas a lo que funcionó. Así aumenta la probabilidad de que tu audiencia las considere de calidad.')]),
        p('Algo importante: la calidad no la decidís vos, la decide tu audiencia. Por eso usamos la cantidad para descubrir qué considera calidad. Y el ciclo no termina: en cuanto creés saber qué le gusta y te concentrás, llegará un punto en que tu audiencia ya no responda igual, y tendrás que volver a abrir el acordeón y probar más.'),
        h3('Cómo saber qué funcionó'),
        p('Si recién empezás y nunca publicaste, hacé doce publicaciones en un mes, por ejemplo tres por semana. Al final vas a notar que algunas funcionaron mejor que otras, y al principio no tenés mucho más en qué basarte. Mirá las visualizaciones, los “me gusta” y los comentarios: qué piezas tuvieron más de esas tres cosas. Probablemente sea un muy buen indicador de qué contenido conviene hacer más.'),
        p('Seguí ensayando hasta sentir que tenés suficiente información. Por ejemplo, si descubrís que explicar tu método paso a paso funciona especialmente bien en una plataforma, ya podés concentrar el esfuerzo y crear más contenido específicamente sobre eso, en distintos formatos.'),
        h3('La regla de los tres cajones'),
        p('Para que tu contenido sea predecible pero no se estanque, te propongo dividir lo que publicás en tres cajones. Es una guía simple, y muy útil.'),
        deflist([('Base (6 de cada 10)', 'Contenido que ya sabés que funciona, gracias al ensayo. No esperes que sea un éxito extraordinario, pero sí que rinda como mínimo el estándar.'),
                 ('Variaciones (3 de cada 10)', 'Lo mismo que funciona, con un pequeño cambio: el gancho, el escenario, la forma de entregarlo o el empaque. Mejorás una variable para ver si rinde más.'),
                 ('Apuestas (1 de cada 10)', 'Ideas nuevas y atrevidas, que pueden salir bien o mal.')]),
        p('El último cajón es el que casi todos descuidan, y es donde más se equivocan. Cuando ya tenés resultados, aparece el miedo a probar algo que rinda menos que tu estándar. Pero necesitás esas apuestas. Quien crea contenido durante más de un año suele experimentar fatiga en su audiencia, y la mayoría entra en pánico: tiene que averiguar de golpe qué quiere ahora su audiencia, justo cuando es urgente.'),
        p('Si incluís las apuestas desde el principio, encontrás la siguiente versión de tu contenido antes de que tu audiencia te diga que la quiere. Terminás construyendo un sistema en el que intentás dejar obsoleto tu propio contenido, antes de que se canse tu audiencia. Y lo curioso es que se va a cansar: siempre pasa.'),
        quote('El mejor momento para reinventar tu contenido es antes de que tu audiencia te lo pida.'),
        exercise('Tu ritmo inicial',
                 p('Elegí una frecuencia que te parezca “casi demasiado fácil”. Anotá cuándo vas a revisarla y cuánto la vas a subir cada vez (por ejemplo, cada trimestre).'),
                 p('Después definí qué tres piezas serían tu base, cuáles tus variaciones y cuál una apuesta para probar este mes. Anotá también cuándo vas a hacer tu primera revisión de resultados.')),
)
