# ---------- INTRODUCCIÓN ----------
chapter('intro', 'Introducción', None, '¿Seguidores<br>o clientes?',
        'Hay una decisión que tomar antes de publicar cualquier cosa: para qué estás construyendo tu marca.', [0, 1, 2, 3],
        lead('En este momento tenés una decisión que tomar: o construís una marca personal para conseguir <b>seguidores</b>, o la construís para conseguir <b>clientes</b>.'),
        p('Vas a escuchar a muchos gurús decirte que necesitás crear el contenido más amplio posible para sumar la mayor cantidad de vistas. Es un consejo que suena lógico: más gente viendo tu contenido debería significar más oportunidades. Pero mi experiencia, y lo que voy a defender a lo largo de todo este libro, es otra: lo único que necesitás es generar <b>confianza verdadera</b> con tu cliente ideal.'),
        p('Las vistas se ven muy bien en una captura de pantalla. Dan una sensación de avance, de que algo está funcionando. Pero no pagan facturas. Una sola persona que confía en vos, que entiende qué problema resolvés y que sabe cómo dar el siguiente paso, puede valer más que mil personas que te dieron un “me gusta” y no volvieron nunca más.'),
        p('Entender esa diferencia cambia todas las decisiones que tomás: qué publicás, a quién le hablás, cuántas veces publicás, qué mostrás de vos y qué no. Por eso la primera pregunta de este libro no es cómo conseguir seguidores. Es qué querés conseguir y para qué.'),
        h3('Un error que se repite todo el tiempo'),
        p('Mucha gente construye su marca personal solo para marcar una casilla. Vio a alguien que admira creando contenido y decidió que ella también debería hacerlo. Nunca se sentó a definir cuál es el resultado que quiere lograr, ni a preguntarse si crear contenido en público es el mejor camino para llegar a ese resultado.'),
        p('Sin ese resultado definido, cada decisión se vuelve una apuesta. No sabés si lo que publicaste estuvo bien o mal, porque no tenés contra qué compararlo. Podés tener mucha actividad y ningún avance. Lo he visto en personas con muchísimo talento: publican con disciplina durante meses, juntan seguidores, y de pronto se dan cuenta de que ninguno de esos seguidores es alguien que podría contratarlas.'),
        p('Por eso este libro no empieza con una estrategia de contenido. Empieza con una pregunta incómoda: ¿realmente necesitás una marca personal pública? Para algunas personas la respuesta es no, y está bien. Para quienes la respuesta es sí, el resto del libro te muestra cómo construirla de forma intencional, sin que te agote y sin que dependa de la suerte.'),
        h3('Qué significa construir una marca personal para conseguir clientes'),
        p('Cuando hablo de marca personal no estoy hablando de ser famoso. Estoy hablando de que las personas correctas sepan quién sos, entiendan qué problema resolvés y confíen lo suficiente en vos como para escribirte, contratarte o recomendarte. Es una infraestructura de tu negocio, no un concurso de popularidad.'),
        compare('Marca para conseguir seguidores', ['Busca la mayor cantidad de vistas posible.', 'Habla de temas amplios para gustarle a todos.', 'Mide el éxito en números de cuenta.', 'Depende de tendencias y de suerte.'],
                'Marca para conseguir clientes', ['Busca que la persona correcta confíe en vos.', 'Habla de problemas concretos de un tipo de persona.', 'Mide el éxito en conversaciones y oportunidades.', 'Se construye con constancia y claridad.']),
        case('Dos cuentas, dos resultados',
             p('Imaginá dos profesionales del mismo rubro. Uno publica consejos amplios, sigue tendencias y consigue muchas vistas, pero casi nadie le escribe para contratarlo. La otra publica poco, siempre sobre un problema muy concreto de un tipo de cliente, y recibe pocos mensajes, pero casi todos son de personas listas para avanzar.'),
             learn('Ninguno de los dos hizo algo “mal”. Optimizaron para cosas distintas. <b>El grupo en torno al cual optimizás es el grupo que más vas a atraer.</b>')),
        quote('Los seguidores aplauden. Los clientes confían, y por eso compran.'),
        h3('Cómo está organizado este libro'),
        p('El libro está dividido en cuatro partes que siguen el orden en que conviene tomar las decisiones. No te saltees ninguna: cada una se apoya en la anterior.'),
        deflist([('Parte 1', 'Antes de empezar: definís qué querés lograr, desde qué lugar vas a hablar y cómo construir una marca que no te agote.'),
                 ('Parte 2', 'Posicionamiento: elegís el problema que resolvés, tu postura distinta y la frase que resume todo.'),
                 ('Parte 3', 'Contenido: aprendés a generar confianza, a hablarle a quien no te conoce y a estructurar cada pieza.'),
                 ('Parte 4', 'Sistema: armás una forma de producir y publicar que puedas sostener durante años.')]),
        p('Al final del libro vas a encontrar un workbook con todos los ejercicios, un plan de acción de 30 días y una biblioteca de ganchos para empezar. Te recomiendo leer cada capítulo y completar el ejercicio antes de pasar al siguiente. El conocimiento que no se aplica se olvida en una semana.'),
        note('todos los ejemplos con personas o negocios que aparecen en este libro son ilustrativos. Los uso para explicar ideas. No son casos reales ni garantizan resultados.'),
)

# ---------- CAPÍTULO 1 ----------
chapter('c1', 'Capítulo', '01', 'Definí tu<br>resultado deseado',
        'Antes de crear contenido, necesitás saber qué querés lograr. A veces la respuesta es que no necesitás crearlo.', [0],
        lead('Antes de hablar de contenido, de plataformas o de seguidores, hay una pregunta que lo ordena todo: <b>¿qué querés lograr?</b>'),
        p('Parece obvio, pero casi nadie se la hace con honestidad. La mayoría empieza a publicar porque “hay que estar”. El problema es que, sin un destino claro, cada decisión se vuelve una apuesta: no sabés qué publicar, a quién hablarle, cuánto tiempo invertirle ni cuándo parar.'),
        p('Mi recomendación es empezar por el final. Definir el resultado que querés y, desde ahí, trabajar hacia atrás hasta el día de hoy. Es lo que llamo <b>ingeniería inversa</b>: en lugar de preguntarte “¿qué hago ahora?”, te preguntás “¿qué tendría que haber pasado para llegar a mi objetivo?” y vas retrocediendo paso a paso.'),
        h3('Un detalle que casi nadie dice: puede que no necesites una marca pública'),
        p('En el mundo del contenido se repite una frase: todos tienen que crear contenido. Y para mucha gente es cierto: es la puerta de entrada a lo que quieren. Pero no para todos. Podés construir un negocio muy sólido sin publicar nunca contenido en público. Lo importante es que lo decidas con los ojos abiertos y no porque “todos lo hacen”.'),
        p('Una buena manera de pensarlo es separar tus objetivos. Supongamos que tenés dos: <b>hacer crecer tu negocio</b> y <b>ayudar gratis a muchas personas que nunca van a ser tus clientes</b>. El primero se podría lograr sin contenido público. El segundo, al menos a gran escala, es muy difícil sin él. Ese análisis te da una respuesta clara sobre si el contenido vale la pena para vos.'),
        p('Además, te da algo valiosísimo: un filtro para tomar decisiones. Cada vez que dudes de si publicar algo, preguntate si ayuda a construir tu negocio o si ayuda a educar gratis a quienes querés ayudar. Si no hace ninguna de las dos cosas, probablemente no vale la pena publicarlo.'),
        h3('Cuando una marca pública te perjudica'),
        case('El profesional de seguridad',
             p('Imaginá a alguien que trabaja en seguridad privada y quiere llegar a proteger a personas muy expuestas. Su trabajo depende de ser discreto: de poder moverse sin que se note su presencia. Si se hace conocido públicamente, puede perder justamente lo que lo hace valioso para ese tipo de cliente.'),
             learn('Hay escenarios en los que ser más visible <b>perjudica</b> el resultado que querés. Por eso la pregunta no es “¿cómo me hago conocido?” sino “¿ser conocido me acerca a lo que quiero?”.')),
        p('No tenés por qué tener la respuesta perfecta hoy. Lo importante es que te hagas la pregunta antes de invertir meses de tu vida en construir algo que podría no llevarte adonde querés.'),
        h3('El mapa inverso: cuatro preguntas'),
        p('Este es el ejercicio con el que empiezo siempre. Son cuatro preguntas que se responden en orden y que, juntas, te dan un mapa de lo que tenés que hacer desde hoy hasta tu resultado. Es muy simple, y justamente por eso funciona.'),
        keybox('Las cuatro preguntas del mapa inverso',
               ol(['<b>Resultado:</b> ¿cuál es el resultado que quiero lograr?',
                   '<b>Reputación:</b> para lograrlo, ¿por qué tendría que ser conocido? Es decir, ¿qué reputación necesito?',
                   '<b>Acciones:</b> para construir esa reputación, ¿qué acciones concretas tengo que repetir día tras día? Nos hacemos conocidos por algo no por decirlo, sino por lo que hacemos.',
                   '<b>Aprendizaje:</b> para hacer esas acciones bien, ¿qué necesito aprender?'])),
        p('Fijate que el orden importa. Si empezás por la última pregunta (“¿qué tengo que aprender?”), vas a terminar estudiando cualquier cosa. Si empezás por la primera, cada cosa que aprendas y cada acción que hagas tiene un propósito.'),
        h3('La pregunta final'),
        p('Cuando terminás de recorrer el mapa, te toca hacerte una última pregunta, la más honesta: crear contenido público, ¿acelera este camino o lo vuelve más lento y difícil? Si la respuesta es que lo acelera, seguimos. Si la respuesta es que lo hace más difícil, te recomiendo no perder más tiempo con esta estrategia y buscar otro camino para tu objetivo.'),
        quote('Si crear contenido no te acerca a tu resultado, no pierdas el tiempo. Si sí, seguimos.'),
        h3('Cómo se ve un mapa inverso completo'),
        case('La nutricionista que quiere llenar su agenda',
             p('Imaginá a una nutricionista que quiere llenar su agenda y arma su mapa inverso así:'),
             p('<b>Resultado:</b> tener la agenda llena de pacientes que sigan el tratamiento hasta el final.'),
             p('<b>Reputación:</b> ser “la nutricionista que explica sin juzgar y con ejemplos de la vida real”.'),
             p('<b>Acciones:</b> publicar una vez por semana la respuesta a una duda real de sus pacientes; contar casos sin datos personales; responder los mensajes que recibe.'),
             p('<b>Aprendizaje:</b> cómo explicar un tema complejo en un minuto, y cómo grabar un video corto con buena luz y buen sonido.'),
             learn('El resultado le dio una guía: ya no publica “lo que está de moda”, publica lo que acerca a la persona correcta.')),
        h3('Errores frecuentes al definir tu resultado'),
        ul(['<b>Resultados vagos:</b> “quiero ser conocido” no es un resultado. “Quiero tener diez clientes nuevos por trimestre” sí lo es.',
            '<b>Resultados que dependen de otros:</b> “quiero que me inviten a un evento” depende de terceros. Elegí uno que dependa de lo que vos hacés.',
            '<b>Confundir seguidores con resultado:</b> los seguidores son un medio, no un fin. Preguntate siempre qué querés que hagan.',
            '<b>Resultados que no te importan de verdad:</b> si lo elegiste porque “suena bien”, vas a abandonar apenas se ponga difícil.']),
        exercise('Tu mapa inverso',
                 p('Respondé las cuatro preguntas en el workbook, en este orden: resultado, reputación, acciones, aprendizaje. Escribí frases cortas y concretas.'),
                 p('Después respondé en una línea: <b>“Crear contenido público, ¿me acerca o me aleja de este resultado?”</b> y justificá tu respuesta con dos motivos. Si la respuesta es que te aleja, escribí qué otro camino podrías explorar.')),
)

# ---------- CAPÍTULO 2 ----------
chapter('c2', 'Capítulo', '02', '¿Estudiante<br>o experto?',
        'Tu punto de partida define cómo tenés que hablar. Fingir ser lo que todavía no sos quema la confianza.', [0],
        lead('Cuando ya sabés qué querés lograr, aparece la pregunta que más cuesta responder con honestidad: <b>¿por qué alguien debería escucharte?</b> Y para responderla, primero tenés que ubicarte: ¿sos el estudiante o sos el experto?'),
        p('Son dos lugares distintos, y los dos son válidos. El problema aparece cuando un estudiante se disfraza de experto. Es uno de los errores que más veo, y lo que consigue es quemar la confianza de la audiencia, algo muy difícil de recuperar. Una persona puede perdonarte que no sepas algo. Es mucho más difícil que te perdone haber fingido saberlo.'),
        h3('El estudiante'),
        p('Si sos estudiante, todavía no tenés grandes victorias ni años de experiencia. No sos la persona que tu audiencia quiere llegar a ser. Pero estás en camino de convertirte en esa persona, y eso también tiene mucho valor.'),
        p('Tu trabajo es ser el representante de tu audiencia. Hacés todas las pruebas, las inversiones y los experimentos que pueden salir bien o mal, y los compartís. Tu contenido documenta cómo mejorás. La audiencia aprende de tus aciertos y también de tus errores, sin tener que pagar el costo de cometerlos.'),
        h3('El experto'),
        p('Si tenés varios logros, si sos la persona en la que tu audiencia quiere convertirse o si ya hiciste lo que ellos quieren lograr, entonces sos el experto. Es posible que te incomode llamarte así, y es comprensible. Pero ocultar lo que lograste no ayuda a nadie.'),
        p('Tu trabajo es enseñar en público. Compartís cómo llegaste adonde estás, los errores que cometiste y que animás a evitar, y también transmitís cómo pasar de donde están a ese nivel más rápido de lo que lo hiciste vos.'),
        compare('El estudiante', ['Todavía no tiene grandes logros ni años de experiencia.', 'No es la persona que su audiencia quiere llegar a ser.',
                                 'Su trabajo es aprender en público y documentar el proceso.', 'Prueba y cuenta qué funciona, como representante de su audiencia.'],
                'El experto', ['Tiene resultados que otros quieren lograr.', 'Hizo lo que su audiencia quiere hacer.',
                               'Su trabajo es enseñar en público.', 'Comparte cómo llegó, qué errores cometió y cómo acortar el camino.']),
        keybox('Una regla de oro',
               p('Si sos estudiante, <b>sé estudiante</b>. No finjas ni aparentes ser el experto. Mucha gente confía más en alguien que aprende con ellos y es honesto sobre eso, que en alguien que finge saberlo todo y se equivoca en público.')),
        h3('Tu banco de pruebas y tu bitácora de aprendizaje'),
        p('Según el lugar en el que estés, te propongo armar una lista que alimente todo tu contenido. Es una herramienta simple, pero te evita quedarte sin ideas y te da de dónde sacar tu credibilidad.'),
        deflist([('Bitácora de aprendizaje', 'Para estudiantes. Una lista continua de lo que estás estudiando, probando y aprendiendo. Tu contenido documenta cómo mejorás.'),
                 ('Banco de pruebas', 'Para expertos. Una lista continua de lo que hiciste, lograste, resolviste y demostraste, incluidos los errores que cometiste y las lecciones que aprendiste.')]),
        p('Algo que quiero que quede muy claro: <b>nunca inventes nada</b> para llenar tu banco de pruebas. Tu credibilidad es lo más valioso que tenés, y una sola exageración descubierta puede dañarla para siempre. Pero sí quiero ser honesto con vos: los resultados que vas a obtener con tu marca dependen en buena medida de lo que pongas en ese banco. Cuanto más sólidos y difíciles de lograr sean los elementos que tengas, más fácil será que tu audiencia te tome en serio y más rápido vas a crecer durante los primeros años.'),
        p('A algunas personas esto les parece injusto. Pero es simplemente cómo funciona la confianza. Y si tu banco todavía es chico, no es un freno para empezar: es una señal de que tenés que ir a hacer cosas valiosas mientras publicás, y compartirlas a medida que las logres.'),
        case('Dos guías de montaña',
             p('Si querés aprender a escalar, no confiás igual en alguien que subió cerros chicos de la zona que en alguien que escaló varias de las cumbres más difíciles del mundo. Los dos pueden enseñarte algo, pero uno tiene mucho más respaldo para decirte “seguí este camino”.'),
             learn('La credibilidad es un multiplicador: <b>cuanto más difícil de lograr es lo que hiciste, más fe tiene tu audiencia en lo que decís.</b>')),
        h3('Qué incluir en cada banco'),
        table2('Banco de pruebas (experto)', 'Bitácora de aprendizaje (estudiante)', [('Resultados que lograste, con números si los tenés', 'Temas que estás estudiando y por qué'),
                                                                                   ('Problemas que resolviste y cómo', 'Cosas que probaste esta semana y qué pasó'),
                                                                                   ('Errores que cometiste y lo que aprendiste', 'Errores de este mes y cómo los vas a corregir'),
                                                                                   ('Proyectos o clientes (sin datos privados)', 'Preguntas que todavía no sabés responder'),
                                                                                   ('Experiencia en distintos escenarios', 'Fuentes y personas de las que estás aprendiendo')]),
        p('Revisá estas listas cada tanto. Con el tiempo se vuelven una mina de ideas para tu contenido y una forma muy concreta de notar cuánto avanzaste.'),
        exercise('Tu punto de partida',
                 p('En el workbook, marcá si hoy sos estudiante o experto en el tema que querés enseñar. Sé honesto: no hay una respuesta mejor que otra.'),
                 p('Después completá la lista que corresponda: 10 cosas que estás aprendiendo y probando, o 10 cosas que lograste y resolviste, con la lección de cada una. Marcá las tres que más podrían servirle a tu audiencia.')),
)

# ---------- CAPÍTULO 3 ----------
chapter('c3', 'Capítulo', '03', 'Una marca que<br>no te agote',
        'La mayoría abandona porque construyó una marca que no disfruta. Elegí una de la que te sientas orgulloso.', [0],
        lead('Casi todos hablan del agotamiento como si fuera un problema de tiempo o de energía. Mi observación es que, en muchos casos, es un problema de <b>marca</b>.'),
        p('Cuando se habla de agotamiento en la creación de contenido, hay dos fuentes distintas. Una tiene que ver con cómo producís (lo vamos a ver en la Parte 4). La otra tiene que ver con qué estás construyendo: qué marca elegiste, de qué temas hablás y quién te parece que tenés que ser frente a la cámara.'),
        p('Mucha gente termina construyendo una marca que odia. Empieza a hablar de temas que en realidad no le interesan ni le apasionan, y de los que ni siquiera es experta. Simplemente ve que esos temas están de moda, que otras marcas personales se construyeron a partir de ellos, y asume que ella tiene que hacer lo mismo. Pasados unos meses, el resultado es previsible: si no te gusta la marca que estás construyendo, no la vas a sostener durante el tiempo que se necesita para obtener resultados.'),
        quote('En lugar de construir la marca que te marca el algoritmo, construí la que te entusiasma.'),
        h3('Una marca de la que te avergüences es una cuenta regresiva'),
        p('Pensá en esta situación: una persona publica videos de manera constante pero nunca se los manda a un amigo cuya opinión le importa. Nunca los comparte con alguien a quien respeta. ¿Por qué? Porque en el fondo se avergüenza de la marca que está construyendo. Y eso, aunque parezca un detalle, es una cuenta regresiva para rendirse.'),
        keybox('La prueba del amigo',
               p('Antes de publicar, preguntate: ¿le enviaría este contenido a un amigo cuya opinión me importa? Si te da vergüenza mandarlo, algo de la marca que estás construyendo no coincide con quién sos. Es mejor detectarlo ahora, no dentro de seis meses.')),
        h3('Dos preguntas para ordenar tus decisiones'),
        p('La mayoría de las personas empieza por preguntarse qué quiere la gente, qué va a tener más vistas o en qué estarán más interesados. Esas preguntas son útiles, pero no son las primeras. Las primeras son estas:'),
        ol(['¿De qué contenido me voy a sentir más orgulloso?', '¿Qué me emociona lo suficiente como para seguir haciendo esto durante años?',
            '¿Qué quiero compartir con el mundo para mostrar quién soy como persona, no una versión curada y caricaturizada de mí que hice para agradarle a un algoritmo?']),
        p('A veces vas a tener que renunciar a decisiones que probablemente te darían más vistas, más suscriptores o mejores números, pero que te llevarían a construir una marca de la que no estarías orgulloso. Esa renuncia, a la larga, es una inversión.'),
        h3('Mostrá a la persona detrás de la marca'),
        p('Tu marca tiene que girar alrededor de un tema principal. Es lo que le da claridad a tu audiencia. Pero no tiene por qué reducirse a una sola cosa. Tampoco vos te definís por una sola cosa. Si sumás algunos elementos personales a tu contenido (un pasatiempo, un gusto, una pasión), le das a tu audiencia más puntos para conectar con vos.'),
        p('Cuando estás conversando con tus amigos, esos temas aparecen de manera natural. Lo ideal es que también aparezcan en tu contenido. Cuanto más cerca está alguien de nosotros, más intereses en común tenemos con esa persona, así que si querés que tu audiencia se acerque a vos, tiene que poder descubrir esos intereses.'),
        p('Mucha gente cree que hablar siempre de una sola cosa es la forma más rápida de crecer. Es posible. Pero también es una forma muy rápida de abandonar la plataforma, porque terminás escondiendo gran parte de quién sos. Mi recomendación es que busques algo sostenible.'),
        case('La arquitecta que habla de su ciudad',
             p('Imaginá a una arquitecta que se especializa en reformas de departamentos chicos. Su tema principal es ese. Pero en sus videos también aparece su pasión por caminar y fotografiar edificios antiguos de su ciudad. Con el tiempo, parte de su audiencia empieza a escribirle por eso y no solo por las reformas.'),
             learn('Lo personal no le resta autoridad. <b>Aumenta las posibilidades de que alguien se identifique con ella.</b>')),
        h3('Lo que no tenés que hacer'),
        ul(['<b>No inventes un personaje.</b> Si no sos extrovertido, no tenés por qué actuar como si lo fueras.', '<b>No copies temas solo porque están de moda.</b> Una tendencia puede ser un formato, pero el tema tiene que seguir siendo tuyo.',
            '<b>No muestres todo.</b> Elegir qué mostrar es válido. Lo importante es que lo que muestres sea cierto.', '<b>No te compares con quienes llevan años.</b> Estás construyendo algo que quieras sostener, no ganando una carrera.']),
        exercise('Tus señales personales',
                 p('Escribí cinco intereses, gustos o pasiones tuyas que no tienen relación directa con tu trabajo. Elegí dos que podrías mencionar con naturalidad dentro de tu contenido.'),
                 p('Después hacé la prueba del amigo con tu idea de marca: escribí tres frases que dirías en tu contenido y preguntate si se las enviarías a alguien que respetás. Por último anotá: <b>“Si en cinco años mirara este contenido, ¿me sentiría orgulloso?”</b>')),
)

# ---------- CAPÍTULO 4 ----------
chapter('c4', 'Capítulo', '04', 'Tu cliente y<br>su problema',
        'Optimizar en torno a tus competidores te da más competidores. Optimizar en torno a tu cliente te da más clientes.', [1],
        lead('Ya sabés qué querés lograr y desde qué lugar vas a hablar. Ahora toca la pregunta que ordena todo tu posicionamiento: <b>¿por qué le importaría esto a tu audiencia?</b>'),
        p('Hasta acá trabajamos en vos: en tu resultado, tu credibilidad y tu marca. Pero tu audiencia no está pensando en vos, está pensando en su propia vida. Y la razón principal por la que consumimos contenido educativo es muy simple: hay un problema que queremos resolver y un dolor del que queremos alivio. Si tu contenido no toca ese dolor, no importa cuán bueno sea.'),
        h3('El error de mirar a tus competidores'),
        p('Un error muy común es observar qué hacen los demás en tu sector y construir tu marca a partir de eso. Parece una estrategia inteligente: “estudio qué funciona y lo hago”. Pero lo que realmente hacés es optimizar en torno a tus competidores y no en torno a tus clientes. Y el grupo para el que optimizás es el grupo que más vas a atraer.'),
        formula(['Optimizás por tus competidores', 'Atraés más competidores'], None),
        formula(['Optimizás por tus clientes', 'Atraés más clientes'], None),
        p('Si querés más competidores mirándote, copiá a tus competidores. Si querés más clientes, escuchá lo que tus clientes realmente quieren y necesitan. No lo que hacen los demás: lo que ellos necesitan.'),
        h3('Cómo empezar: el dolor de tu cliente'),
        p('Para ponerte en el lugar de tu cliente, empezá preguntándote cuál es el dolor que está enfrentando. Un dolor es un problema concreto que le quita tiempo, plata, tranquilidad o confianza, y del que quiere salir. Cuanto más específico sea, mejor.'),
        keybox('Cómo reconocer un buen problema para trabajar',
               ul(['Tu cliente lo reconocería enseguida si lo leyera.', 'Es algo que le preocupa a diario o lo frustra con frecuencia.', 'Ya intentó resolverlo y no lo logró.', 'Estarías dispuesto a hablar de eso durante meses.'])),
        p('Fijate también en lo que cree que está haciendo bien pero en realidad hace mal. Muchos de los problemas más valiosos son esos: el cliente ni siquiera sabe que lo tiene.'),
        h3('Pensá en la persona que siempre arregla cosas'),
        p('Seguro tenés a alguien en tu vida a quien acudís cuando algo se rompe: un amigo que siempre sabe de computadoras, un familiar que entiende de trámites. No solo vas vos. También se lo recomendás a tus familiares y amigos cuando tienen el mismo problema.'),
        p('Si te hacés conocido como alguien que resuelve los problemas de tu cliente ideal, pasa exactamente lo mismo: más personas van a acudir a vos. Esa es la diferencia entre ser conocido por generar buen contenido y ser conocido por resolver problemas reales. El contenido genial consigue atención. Resolver problemas consigue <b>confianza</b>.'),
        keybox('Tu base de trabajo',
               formula(['Problema doloroso del cliente', 'Tu solución distinta'], 'Esta combinación es el corazón de tu mensaje', '+')),
        case('El contador que se vuelve la persona de confianza',
             p('Imaginá a un contador que sabe que sus clientes pequeños sienten miedo de equivocarse con los impuestos. En vez de publicar leyes y normativa, publica “los cinco errores que veo cometer a los dueños de negocios al organizar su caja”, y para cada error explica cómo evitarlo con un paso concreto.'),
             learn('No es un contenido espectacular. Es <b>útil para una persona concreta</b>, y por eso genera confianza.')),
        h3('Cómo encontrar los problemas de tu cliente'),
        ol(['<b>Escuchá las conversaciones reales:</b> preguntas que te hacen, dudas que repiten, quejas sobre cómo lo resolvieron antes.', '<b>Mirá lo que te piden en privado:</b> los clientes de alto valor suelen escribir por mensaje y no en comentarios públicos.',
            '<b>Preguntales directamente:</b> “¿Qué es lo más difícil de esto hoy?” y “¿qué probaste y no te funcionó?”.', '<b>Anotá sus palabras exactas:</b> son tus mejores títulos y ganchos.']),
        p('Mientras más problemas dolorosos identifiques, más ideas de contenido vas a tener para el futuro. Por eso conviene mantener una lista viva, que revisás cada cierto tiempo.'),
        h3('Errores frecuentes'),
        ul(['<b>Elegir problemas que a vos te interesan pero a tu cliente no.</b> Es el error más común entre los expertos.', '<b>Hablar de síntomas y no del dolor real.</b> Detrás de “no consigo clientes” puede haber falta de claridad en la oferta.',
            '<b>Usar tu lenguaje técnico.</b> Tu cliente describe su problema con otras palabras.', '<b>Tener una solución igual a la de todos.</b> Tu solución distinta es lo que te diferencia.']),
        exercise('Tu lista de problemas',
                 p('Escribí entre 10 y 15 problemas dolorosos que tiene tu cliente ideal. Usá sus palabras, no las tuyas. Si no te salen tantos, escribí los que puedas.'),
                 p('Para cada problema, anotá en una línea cuál es tu solución distinta. Marcá los tres problemas más dolorosos: van a ser la base de tu contenido durante los próximos meses.')),
)
