# ---------- CAPÍTULO 5 ----------
chapter('c5', 'Capítulo', '05', 'Tu postura<br>distinta',
        'Es la palanca más fuerte para destacar: lo que creés de verdad aunque la mayoría del sector piense otra cosa.', [1],
        lead('Hoy hay más creadores de contenido que nunca. Si sentís que tu sector está saturado, tenés razón. Hay tanta gente hablando de lo mismo que cuesta distinguir una voz de otra. La pregunta es cómo destacar. Y mi respuesta es una sola: con tu <b>postura distinta</b>.'),
        p('Para destacar entre tantos creadores hay tres palancas que podés accionar. Dos de ellas están en tu contenido y las vamos a ver en la Parte 3. La primera, y la más importante, es tu postura distinta. Para mí es la que más retorno da: podés combinar las otras dos y aun así no se acercan al efecto de tener una postura clara que sea realmente tuya.'),
        p('Es lo que hace que, entre diez personas que enseñan el mismo tema, la gente recuerde a una. No porque enseñe más ni mejor, sino porque defiende algo que las demás no defienden. Pero antes de seguir, tengo que aclarar algo que se confunde mucho.'),
        h3('Postura distinta no es lo mismo que polémica'),
        p('Cuando hablo de una creencia contraria o de un punto de vista distinto, mucha gente lo interpreta como “ser polémico”. No es lo mismo, y la diferencia es enorme. Jamás te recomendaría ser polémico solo por serlo: es una estrategia que, a la larga, te perjudica.'),
        compare('Postura distinta', ['Vas en contra de la creencia dominante porque realmente lo creés.', 'Te resulta imposible no decirlo, porque en el fondo lo sentís cierto.', 'Genera coherencia con el paso del tiempo.', 'Atrae a quienes piensan como vos.'],
                'Postura polémica', ['Elegís una opinión porque sabés que va a provocar.', 'Diseñás tus frases para obtener una reacción.', 'Te vuelve una persona impredecible.', 'Aleja a quienes quieren asociarse con vos.']),
        p('Quienes trabajan con marcas personales muy sólidas suelen ser muy cuidadosos con las personas con las que se asocian. Evitan a quienes construyeron su marca sobre la polémica, porque no saben hacia dónde puede ir esa controversia. Si querés que otros confíen en vos y se asocien con vos, te conviene ser alguien predecible en tus valores, aunque no en tu manera de decir las cosas.'),
        h3('Dos ejemplos de posturas distintas que cambiaron una industria'),
        deflist([('Una marca de ropa outdoor', 'Apostó por priorizar el cuidado del medio ambiente por encima de las ganancias, en una industria donde se priorizaba el consumo masivo. Sus acciones respaldaron esa postura, y hoy es referencia de empresa guiada por valores y no solo por beneficios.'),
                 ('Una plataforma de series', 'Creyó que la gente no quería salir de casa para elegir una película en un local de alquiler. Primero la enviaba por correo; después evolucionó hasta que ni siquiera había que abrir la puerta. Esa creencia, que parecía una locura, cambió toda la industria del entretenimiento.')]),
        learn('Fijate cómo, mirando hacia atrás, esas posturas parecen obvias. Pero en su momento eran <b>contrarias a lo que todos creían</b>. Y ese es justamente su poder.'),
        h3('Cómo encontrar la tuya: la tabla de desacuerdos'),
        p('Quizás ya sepas cuál es tu postura. Muchas personas la tienen clara desde hace años: cuando escuchan cierto consejo en su sector, sienten un rechazo inmediato. Esa reacción es una pista valiosa. Si te pasa, anotá exactamente qué es lo que te molesta.'),
        p('Si no te sale, usá este ejercicio simple. Lo llamo la tabla de desacuerdos:'),
        keybox('Cómo armarla',
               ol(['Dibujá dos columnas.', 'En la izquierda, escribí todo lo que la gente de tu sector dice o hace y con lo que no estás de acuerdo: afirmaciones, consejos, métodos, formas de atender a los clientes.',
                   'Incluí también lo que hacen tus competidores y que a tus clientes les molesta (por ejemplo, tardar en responder o ser desorganizados).', 'En la derecha, escribí qué pensás vos, o qué cambiarías.'])),
        p('El resultado es una lista de posturas posibles. No hace falta que todas sean brillantes. Algunas van a ser más fuertes que otras, y lo vas a notar al probarlas.'),
        case('El entrenador personal',
             p('Un entrenador anota en su tabla: “Dicen que hay que entrenar todos los días sin descansar” (izquierda) y “Creo que el descanso es parte del entrenamiento” (derecha). También: “Dicen que hay que bajar de peso rápido para motivarse” y “Creo que un cambio lento y sostenido dura mucho más”. Y: “Mis colegas responden tarde los mensajes” y “Yo respondo en el día”.'),
             learn('De esa tabla salen <b>tres posturas</b>: descanso, ritmo lento y atención rápida. Todas son posibles para probar en el contenido.')),
        h3('Probá varias y fijate cuál resuena'),
        p('Una vez que tenés dos o tres posturas, no tenés que elegir a ciegas. Probalas en tu contenido durante un tiempo y observá cuál conecta más con tu audiencia. La que más resuene es la que conviene reforzar.'),
        p('¿Cómo saber si está resonando? Hay señales muy claras:'),
        ul(['<b>Te citan:</b> la gente comenta tu frase de vuelta, con tus propias palabras.', '<b>Te escriben más:</b> después de publicar contenido sobre esa postura, recibís más mensajes privados de lo habitual y mencionan esa pieza.',
            '<b>Hablan de vos:</b> personas que no conocés empiezan a mencionarte o etiquetarte al hablar de ese tema.', '<b>Te piden más:</b> aparecen preguntas de seguimiento sobre esa postura en particular.']),
        p('Cuando una postura se destaque, en lugar de intentar imponer todas tus ideas a la audiencia, <b>insistí con ella</b>. Repetila una y otra vez. Es la que tu audiencia está pidiendo que defiendas, y probablemente también sea una de las que más te apasiona.'),
        h3('Errores frecuentes'),
        ul(['<b>Elegir una postura que no sentís</b> solo porque suena fuerte. Se nota, y no la vas a poder sostener.', '<b>Hacerla demasiado general.</b> Una postura útil dice algo concreto sobre tu sector.', '<b>Atacar a personas.</b> Tu postura es una idea, no una pelea.',
            '<b>Cambiarla cada semana.</b> Necesita repetición para asociarse con vos.']),
        exercise('Tu tabla de desacuerdos',
                 p('Completá en el workbook la tabla de desacuerdos con al menos 6 filas. Anotá cosas que dice la gente, cosas que hace y cosas que pensás distinto.'),
                 p('Subrayá las 2 o 3 posturas que más te importan. Elegí una para empezar a probarla en tu contenido esta semana y anotá cuáles serán las señales que vas a observar para saber si resuena.')),
)

# ---------- CAPÍTULO 6 ----------
chapter('c6', 'Capítulo', '06', 'Cómo funciona<br>realmente una marca',
        'Branding es asociarte con algo de manera repetida. La marca es el resultado de esa repetición.', [1],
        lead('Antes de usar las palabras “marca” y “branding” en tu estrategia, conviene darles una definición clara. Mucha gente las usa como sinónimos de logo, colores o diseño. Para mí son otra cosa.'),
        deflist([('Branding', 'Asociarte de manera constante con ciertas ideas, personas y acciones.'),
                 ('Marca', 'El resultado de esas asociaciones en la mente de tu audiencia.')]),
        p('Esta definición tiene una consecuencia muy práctica: una marca no es algo que anunciás, es algo que <b>se construye con repetición</b>. No importa cuánto digas que sos “innovador” o “confiable”: lo que cuenta es con qué te asociás de forma consistente.'),
        formula(['Asociación', 'Constancia'], 'La regla de las repeticiones', '×'),
        p('Lo que repetís con constancia es lo que tu audiencia termina asociando con vos. Parece simple, y lo es. Pero es el mecanismo detrás de cualquier marca fuerte.'),
        h3('Cómo se ve en una empresa'),
        case('Lo que se asocia con una empresa de tecnología',
             p('Si una empresa se asocia durante muchos años de manera constante con un diseño simple, elegante y cuidado, cuando pensamos en ella lo primero que viene a la mente es el diseño, no el procesador ni las especificaciones técnicas. Esa asociación se construyó con repetición durante décadas, no de un día para otro. Cada producto, cada anuncio y cada declaración reforzaban la misma idea.')),
        h3('Cómo se ve en una persona'),
        case('Las historias de una red social',
             p('Conocés a alguien nuevo y lo empezás a seguir. Si cada semana sube canciones de un género musical en particular, vas a asumir que le gusta ese género. Nunca te lo dijo. Lo dedujiste porque lo repite.'),
             p('Y si en el pasado conociste a otras personas a las que les gustaba ese género, no solo vas a asociar a esta persona con la música: la vas a asociar con todo lo que ese gusto significa para vos.'),
             learn('Hacemos exactamente lo mismo con las marcas. <b>Lo que repetís es lo que te define.</b>')),
        h3('También funciona para lo que no querés'),
        p('Este mecanismo funciona con la misma fuerza en sentido contrario. Si te mostrás de manera constante con personas, ideas o acciones opuestas a la marca que querés construir, tu audiencia va a asociarte con eso. Una asociación negativa se construye igual que una positiva.'),
        p('Pensá en alguien que quiere construir una marca confiable y aparece constantemente con personas conocidas por no cumplir lo que prometen. Aunque él cumpla, su audiencia empezará a preguntarse si es tan confiable como dice. Por eso conviene ser cuidadoso con las palabras que decís, con las personas con las que aparecés en público y con lo que compartís.'),
        h3('Asociaciones deseadas: ingeniería inversa'),
        p('La buena noticia es que podés elegir tus asociaciones en lugar de dejarlas al azar. Para eso, aplicá la misma lógica de ingeniería inversa del primer capítulo:'),
        ol(['<b>Elegí dos asociaciones por las que querés ser conocido.</b> Por ejemplo: “claridad” y “constancia”.', '<b>Elegí dos asociaciones contra las que querés ser conocido.</b> Por ejemplo: “promesas exageradas” y “soluciones rápidas”.',
            '<b>Preguntate con qué necesitás vincularte de manera constante</b> para lograr esas asociaciones. Eso te da acciones concretas.']),
        p('Así como construís tu marca en torno a lo que buscás, también conviene que seas claro con lo que no estás dispuesto a hacer. Muchas marcas de lujo lo hacen muy bien: no solo dicen para quién es su producto, también dejan claro para quién no. Eso genera exclusividad para la audiencia que realmente querés atraer.'),
        p('Y la ventaja es enorme: deja de ser cuestión de suerte, como tirar de la palanca de una máquina tragamonedas y esperar a ver qué sale. Te vuelve intencional y no dependés de las suposiciones.'),
        h3('Cuidado con lo que prometés en público'),
        p('Quien recién empieza puede pensar que no hay amenazas para su marca. Pero hay un riesgo del que casi nadie habla: lo que decís hoy, públicamente, moldea cómo te va a ver tu audiencia durante mucho tiempo, y lo que afirmás con fuerza te lo van a exigir durante años.'),
        p('Imaginá que decís en tus primeros videos que odiás cierto tipo de contenido o cierto formato. Dentro de tres, cuatro o cinco años, puede que ese mismo formato sea justo lo que tu negocio necesita. Y vas a tener que lidiar con el hecho de que lo criticaste en público. Podés cambiar de opinión, y cambiar de opinión es válido. Pero las críticas que vengan con el cambio las vas a tener que atravesar.'),
        keybox('Una pregunta antes de publicar una postura firme',
               p('<b>¿Voy a estar orgulloso de decir esto dentro de cinco o diez años?</b> Si es algo por lo que pelearías, decilo con toda claridad. Si no, quizás vale la pena pensar si realmente querés decirlo en público. Una postura apresurada puede convertirse en una jaula de la que tu marca no puede escapar.')),
        case('El creador que prometió que todo sería gratis',
             p('Un creador repite durante mucho tiempo que solo va a regalar contenido gratuito y que nunca va a vender nada. Años después, cuando necesita presentar una oferta paga, parte de su audiencia se molesta. La expectativa que él mismo construyó se volvió una restricción.'),
             learn('Podés cambiar de postura, pero <b>cambiar de postura en público tiene un costo</b>. Elegí con cuidado lo que afirmás con absoluta firmeza.')),
        p('No te estoy diciendo que dejes de tomar posturas fuertes. Te digo que mantengas abiertas tus opciones en todo aquello que no sea esencial para vos, y que reserves la firmeza total para lo que realmente creés que no va a cambiar.'),
        exercise('Tus asociaciones',
                 p('Escribí dos asociaciones por las que querés ser conocido y dos contra las que querés ser conocido. Para cada una, anotá una acción concreta que podés repetir cada semana para reforzarla (o evitarla).'),
                 p('Después revisá tu contenido reciente o tus mensajes públicos: ¿hay algo que refuerce una asociación que no querés? Anotá qué cambiarías.')),
)

# ---------- CAPÍTULO 7 ----------
chapter('c7', 'Capítulo', '07', 'Tu frase<br>ancla',
        'Una frase clara que resuma a quién ayudás, cómo y por qué sos distinto. La vas a repetir muchas veces.', [1],
        lead('Cuando ya tenés tu postura distinta, necesitás convertirla en una sola frase corta que puedas decir en cualquier situación. La llamo <b>frase ancla</b>, porque es lo que mantiene fija tu marca cuando todo lo demás cambia.'),
        p('Su función es resumir de manera clara tres cosas: <b>a quién ayudás</b>, <b>cómo lo ayudás</b> y <b>qué hacés distinto de tu competencia</b>. Cuando las tres cosas están dichas en una sola frase, le facilitás muchísimo a tu cliente ideal la decisión de elegirte o de no elegirte.'),
        p('Y esto es más importante de lo que parece. Queremos que sea fácil decidir, no solo para comprar y convertirse en cliente, sino también para decidir si vale la pena consumir tu contenido. Una persona que entiende en cinco segundos si algo es para ella es una persona que se queda o se va con claridad.'),
        h3('Por qué una frase y no un discurso'),
        p('Una frase corta se repite, se recuerda y se comparte. Un discurso largo se olvida. Pensá en cualquier marca que recordás: casi siempre es por una idea simple y repetida muchas veces. Para que tu audiencia haga la asociación entre vos y tu postura, tiene que poder resumirla en una frase y recordarla.'),
        keybox('Una fórmula simple para armarla',
               formula(['Para [tu audiencia]', 'que quiere [su deseo principal]', 'creo que deberían [tu postura]', 'y no [la creencia común del sector]'], None, '·')),
        p('No es la única forma de escribir una frase ancla. Hay otras maneras. Pero esta es simple y efectiva, y te obliga a incluir los elementos clave. Si completás los cuatro espacios, vas a tener algo que podés repetir despierto, cansado, de buen o de mal humor.'),
        h3('Tres ejemplos ilustrativos'),
        deflist([('Entrenamiento', 'Creo que las personas ocupadas que quieren ponerse en forma deberían entrenar menos tiempo pero con más constancia, y no seguir rutinas largas que abandonan al mes.'),
                 ('Finanzas', 'Creo que los emprendedores que quieren ordenar su dinero deberían empezar por entender su flujo de caja, y no por buscar inversiones.'),
                 ('Diseño', 'Creo que los negocios pequeños que quieren verse profesionales deberían invertir en mensajes claros, y no en logos complicados.')]),
        p('Fijate qué comunican esas tres frases: dicen a quién le hablan, qué quiere esa persona y qué creencia común están poniendo en duda. Una persona que lee cualquiera de ellas sabe en pocos segundos si es para ella.'),
        h3('Cómo se escribe una buena frase ancla'),
        ol(['<b>Hacé varias versiones.</b> La primera casi nunca es la mejor. Escribí al menos tres.', '<b>Leelas en voz alta.</b> Si te cuesta decirlas con naturalidad, hay palabras que sobran.',
            '<b>Sacá las palabras vagas.</b> “Mejores resultados” o “crecer” no dicen nada concreto. Cambialas por algo específico.', '<b>Probala con una persona que no conoce tu trabajo.</b> Preguntale qué entendió. Si no coincide con lo que querés decir, ajustala.']),
        note('escribir esta frase lleva más tiempo del que parece. Se ve muy simple cuando la escuchás, pero al sentarte a escribirla cuesta. Reservá un rato tranquilo para hacerlo bien.'),
        h3('Para qué sirve repetirla'),
        p('Repetirla es lo que hace la diferencia. Una frase ancla que escribiste y guardaste en un cajón no sirve de nada. La idea es que la digas en tus videos, en entrevistas o conversaciones, en tu biografía, en tus publicaciones y en cada lugar donde tengas oportunidad.'),
        p('Es como la asociación de la que hablamos en el capítulo anterior: cuanto más la repetís, más se asocia con vos. Con el tiempo, quienes te siguen van a terminar diciéndola antes que vos. Es una señal excelente: significa que tu mensaje ya está en la cabeza de tu audiencia.'),
        quote('Mi test: si podés decir tu frase ancla hasta medio dormido, está lista.'),
        case('Una frase que se vuelve una respuesta',
             p('Alguien publica un contenido que contradice tu postura, diciendo que lo único que importa es la cantidad de vistas. Antes de que vos respondas, otras personas de tu audiencia ya le explican que tu enfoque es otro. Ya conocen tu frase y la usan.'),
             learn('Cuando tu audiencia defiende tu postura sin que se lo pidas, <b>tu marca ya existe</b>.')),
        h3('Errores frecuentes'),
        ul(['<b>Una frase que sirve para todos.</b> Si cualquiera podría decirla, no te diferencia.', '<b>Demasiado larga.</b> Si no podés decirla de un tirón, no se va a recordar.', '<b>Solo dice qué hacés, no qué creés.</b> Lo que te distingue es tu postura.', '<b>No usarla.</b> Una frase que no aparece en tu contenido no construye ninguna asociación.']),
        exercise('Tu frase ancla',
                 p('Completá la fórmula en el workbook con al menos tres versiones distintas. Leelas en voz alta y elegí la que se entienda mejor sin necesidad de explicación.'),
                 p('Después contásela a una persona que no conozca tu trabajo y preguntale qué entendió y qué piensa que hacés. Si lo que dice no coincide con lo que querías transmitir, reescribila. Anotá la versión final.')),
)

# ---------- CAPÍTULO 8 ----------
chapter('c8', 'Capítulo', '08', 'Confianza antes<br>que alcance',
        'Con una oferta de alto valor para un público reducido, el contenido amplio puede alejarte de quien sí te compraba.', [2],
        lead('Ahora que entendés tu marca, es momento de amplificarla con una estrategia de contenido. Y lo primero que tengo que aclarar es el debate más grande de todos: <b>alcance o confianza</b>.'),
        p('Quiero ser justo: hay negocios en los que volverse viral es muy valioso, por ejemplo los que venden un producto de consumo masivo y de bajo precio. Para ellos, el alcance es una herramienta central. Pero si vendés una oferta de alto valor a un grupo muy específico y reducido de personas, lo viral no es tan útil como algunos te hacen creer.'),
        p('Voy a asumir en este capítulo que estás en este segundo caso, porque es el más común en servicios profesionales, consultorías y formación. Si es tu caso, te conviene entender cómo suele funcionar, en la práctica, la optimización por viralidad.'),
        h3('Qué suele pasar cuando optimizás por viralidad'),
        p('Para ganar alcance tenés que crear contenido más amplio, que le guste a más gente. Y lo amplio suele <b>diluir</b> el mensaje. Es como agregar agua a un jugo concentrado: seguís teniendo líquido, pero ya no tiene el mismo sabor. Atrae más vistas y más seguidores, pero también atrae a personas que no tienen un interés real en lo que ofrecés.'),
        p('Y lo que ocurre después es silencioso. Al principio construiste tu audiencia en torno a resolver problemas concretos. Con el tiempo, a medida que tu contenido se vuelve más general, dejás de resolver esos problemas. Las personas que te compraban dejan de consumir tu contenido porque ya no les sirve. Las nuevas que llegan no tienen interés en lo que vendés.'),
        formula(['Contenido cada vez más general', 'Dejás de resolver los problemas de tu cliente', 'Tus clientes se van', 'Suben las vistas y bajan las ventas'], 'El camino que conviene evitar'),
        case('La nutricionista que se volvió “general”',
             p('Una nutricionista empieza ayudando a personas con diabetes a organizar sus comidas. Con el tiempo, para ganar vistas, empieza a publicar “10 desayunos famosos” y “qué comen los deportistas”. Los números suben. Pero sus pacientes potenciales ya no encuentran respuestas a sus problemas y dejan de seguirla. La agenda se vacía.'),
             learn('Lo peor es lo silencioso: <b>no te das cuenta mientras pasa</b>, hasta que un cliente ideal te dice “hace meses que no veo tus videos porque ya no me ayudan”.')),
        p('Es parecido a lo que pasa con el peso: un día te despertás y notás que subiste varios kilos, y no sabés en qué momento sucedió. Prestar atención a esto a tiempo es mucho más fácil que corregirlo después.'),
        h3('Qué es realmente la confianza'),
        p('Para optimizar por confianza, primero hay que definirla. Esta es la definición que uso y que me resulta muy útil: <b>la confianza es cuánto creés que alguien o algo va a cumplir tus expectativas en el futuro, en base a cómo se comportó en el pasado</b>.'),
        p('Un ejemplo sencillo: si salís a encender tu moto o tu auto todos los días y arranca, confiás en él. Si un día presionás el botón y no arranca, al día siguiente ya no estás tan seguro. La confianza se construye con cumplimiento repetido y se erosiona con incumplimiento.'),
        h3('Cómo optimizar tu contenido para generar confianza'),
        keybox('Cuatro pasos simples y repetibles',
               ol(['<b>Identificá</b> qué problema doloroso resolvés para tu cliente ideal.',
                   '<b>Explicá</b> cuál es tu solución distinta a ese problema: qué hacés diferente de los demás.',
                   '<b>Establecé la expectativa</b>: antes de empezar, aclarale qué problema vas a ayudar a resolver en esa pieza.',
                   '<b>Facilitá la acción</b>: mostrale qué pasos tiene que dar para llegar al resultado.'])),
        p('Si repetís esto una y otra vez, tu audiencia desarrolla una creencia sólida: <b>vas a cumplir, o incluso superar, lo que prometés</b>. Y esto tiene una consecuencia comercial importante: cuando algún día les presentes una oferta, la probabilidad de que crean que vas a cumplir también con esa oferta es mucho mayor. Es la repetición de acciones durante meses lo que construye ese patrón de confianza.'),
        p('Es decir: confiar en vos no es un sentimiento abstracto. Es el resultado acumulado de todas las veces que cumpliste.'),
        h3('¿A quién escuchar para decidir qué publicar?'),
        p('Mucha gente discute si hay que leer cada comentario y tomarlo como palabra sagrada, o ignorarlos por completo. Creo que debe existir un punto medio, y que depende de tu oferta.'),
        table2('Tu oferta', 'Dónde conviene escuchar', [('Barata y para mucha gente', 'La sección de comentarios. Allí hay más personas que reflejan cómo es tu comprador.'),
                                                       ('De alto valor y para pocos', 'Tus clientes: sus mensajes privados, sus preguntas de seguimiento y lo que más piden.')]),
        p('Quien compra un servicio de alto valor suele escribirte por mensaje privado, por correo o por teléfono en lugar de comentar en público. Por eso, si tenés ese tipo de oferta, la información más valiosa suele estar en esas conversaciones. Eso no significa que ignores a quienes comentan: simplemente que la fuente principal de decisiones tiene que ser tu cliente ideal.'),
        quote('Si querés más seguidores, escuchá a tus seguidores. Si querés más clientes, escuchá a tus clientes.'),
        exercise('Tu fuente de ideas',
                 p('Anotá dónde vas a escuchar a tus clientes: mensajes privados, reuniones, preguntas frecuentes, correos.'),
                 p('Escribí las cinco preguntas que más te hicieron en el último mes y convertí cada una en una idea concreta de contenido. Después escribí una frase: <b>“Para mi negocio, optimizo por ______ y no por ______”.</b>')),
)

# ---------- CAPÍTULO 9 ----------
chapter('c9', 'Capítulo', '09', 'Hablale a quien<br>todavía no te conoce',
        'Si solo hablás para quienes ya te siguen, nunca vas a sumar gente nueva.', [2],
        lead('Un error muy común en creadores y emprendedores: asumir que la audiencia sabe quién sos. <b>No lo sabe.</b>'),
        p('Es fácil caer en esto. Con el tiempo empezás a hacer chistes internos, a mencionar nombres y proyectos sin explicarlos y a referirte a cosas que solo entienden quienes te siguen hace años. Es natural: hablás con tu audiencia habitual y se genera cierta complicidad. El problema es que cada pieza de contenido que publicás puede ser la primera que alguien vea tuya.'),
        p('Quizás ya lo viste en otros creadores o lo hiciste vos mismo: contenido pensado para una comunidad cálida, con referencias que el resto no entiende. Para el que llega por primera vez, es como entrar a una fiesta donde todos se conocen y nadie te presenta.'),
        quote('Hacé cada contenido como si la persona que lo ve te estuviera conociendo por primera vez.'),
        h3('Audiencia fría y audiencia cálida'),
        compare('Audiencia fría', ['No sabe quién sos.', 'Llega por un problema o una curiosidad.', 'Necesita contexto y una razón para quedarse.'],
                'Audiencia cálida', ['Ya te conoce.', 'Confía en tu criterio.', 'Entiende tus referencias internas.']),
        p('Un ejemplo muy simple: si hablás de un familiar o de un amigo y nombrás a esa persona sin explicar quién es, tus conocidos lo entienden de inmediato, pero un grupo nuevo no sabe de quién hablás. Hay que aclararlo. Esa misma forma de pensar tenés que aplicarla a tu marca.'),
        p('Pensar en la audiencia fría cambia cómo contextualizás todo: cómo te presentás, cómo explicás tus ideas, qué credenciales mencionás y cómo cerrás cada pieza. Si optimizás para una audiencia cálida, simplemente vas a continuar con la que ya tenés y te va a costar mucho traer gente nueva. Si optimizás para una fría, vas a atraer más gente nueva. Es el mismo principio de siempre: el grupo para el que optimizás es el que más vas a atraer.'),
        h3('La puerta abierta'),
        p('Una imagen que me gusta usar: la audiencia fría es alguien que llegó hasta tu puerta. Tenés que abrirla, invitarlo a pasar y hacerle sentir que hay un lugar cómodo. Así es como convertís a alguien de audiencia fría en audiencia cálida. Y no lo vas a lograr si esa persona ni siquiera entiende de qué hablás al principio del contenido.'),
        h3('Primero entendé tu marca, después comunicala'),
        p('Para poder explicar a una audiencia fría qué es tu marca y qué representás, primero tenés que entenderlo vos. Por eso trabajamos en todo lo anterior antes de hablar de contenido. Mucha gente quiere saltar directamente a la estrategia: “¿qué contenido me va a conseguir un millón de vistas?”. Pero si conseguís ese millón de vistas con una marca que no entendés, ¿cómo van a entender esas personas qué representás? No lo van a entender.'),
        h3('El balde con fugas'),
        p('Pero no alcanza con atraer gente nueva. También tenés que cuidar a la que ya llegó. Si optimizás solo para audiencia nueva y no nutrís a la actual, tu audiencia es como un balde con fugas: sumás agua todo el tiempo, pero también se escapa, y te quedás igual. Por cada persona nueva que entra, una de las actuales se va. Los números no mejoran, y mucho menos las conversiones de tu negocio.'),
        keybox('Lo ideal: hacer los dos tipos de contenido',
               ul(['<b>Contenido para audiencia fría:</b> cada pieza se entiende por sí sola y presenta tu marca.', '<b>Contenido para audiencia cálida:</b> profundiza, resuelve dudas y premia la lealtad de quienes ya confían en vos.'])),
        p('Esto es algo que puede costar al principio. Si estás en tu primer año, probablemente te conviene enfocarte más en la audiencia fría, porque todavía tenés poco que nutrir. A medida que crezcas, vas a ir equilibrando los dos tipos.'),
        h3('La fórmula de tu contenido'),
        p('Cada pieza que creás es un regalo para tu audiencia. Y ese regalo se arma con tres ingredientes: el problema y la solución (el contenido en sí), tu credibilidad para hablar de ese tema y una buena presentación.'),
        formula(['Problema doloroso + tu solución distinta', '× credibilidad contextual', '× una buena presentación'], 'Cómo se arma una pieza que funciona', ''),
        p('De esos tres ingredientes, el del medio es el que más se subestima: la <b>credibilidad contextual</b>. Es la diferencia entre decir lo que hiciste en general y decir lo que hiciste exactamente en el tema del que vas a hablar.'),
        deflist([('Credibilidad general', 'Lo que te hace una persona confiable en tu campo, en términos amplios: “llevo muchos años en este sector”.'),
                 ('Credibilidad contextual', 'Lo que te hace confiable para el tema específico de ese contenido. Es la más poderosa.')]),
        case('Dos presentaciones de la misma persona',
             p('Una diseñadora puede decir “llevo muchos años trabajando” (credibilidad general), o puede decir “rediseñé la identidad visual de más de cuarenta negocios pequeños de gastronomía” antes de hablar de identidad para restaurantes (credibilidad contextual).'),
             learn('Cuanto más <b>contextual</b> sea tu credibilidad, más va a creer tu audiencia lo que estás por decir.')),
        p('Un detalle más: la comparación importa. Quien logró cierto resultado en cinco años y quien logró el mismo en diecisiete son dos casos distintos para el público. La experiencia en varios escenarios hace pensar que lo que enseñás son principios aplicables a distintos casos, y no algo que funcionó una sola vez. Cuanto más contextual y variada sea tu credibilidad, más va a creer tu audiencia que puede aplicar lo que enseñás.'),
        exercise('Problema, solución y prueba',
                 p('Para cada uno de los problemas de tu lista del capítulo 4, escribí tu solución distinta y una frase de credibilidad contextual que podrías decir al comenzar ese contenido.'),
                 p('Si tenés más de una versión posible de tu credibilidad, mejor: no vas a hacer un solo contenido sobre ese problema, vas a hacer varios durante los próximos años. Anotá también una versión de credibilidad general para usar cuando haga falta.')),
)
